package mybatis.two.mapper;

import java.util.List;
import mybatis.two.po.DBMTMContact;
import mybatis.two.po.DBMTMContactExample;
import mybatis.two.po.DBMTMContactKey;
import org.apache.ibatis.annotations.Param;

public interface DBMTMContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTMContact
     *
     * @mbggenerated
     */
    int countByExample(DBMTMContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTMContact
     *
     * @mbggenerated
     */
    int deleteByExample(DBMTMContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTMContact
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(DBMTMContactKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTMContact
     *
     * @mbggenerated
     */
    int insert(DBMTMContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTMContact
     *
     * @mbggenerated
     */
    int insertSelective(DBMTMContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTMContact
     *
     * @mbggenerated
     */
    List<DBMTMContact> selectByExample(DBMTMContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTMContact
     *
     * @mbggenerated
     */
    DBMTMContact selectByPrimaryKey(DBMTMContactKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTMContact
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DBMTMContact record, @Param("example") DBMTMContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTMContact
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DBMTMContact record, @Param("example") DBMTMContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTMContact
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DBMTMContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTMContact
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DBMTMContact record);
}