package mybatis.two.po;

import java.io.Serializable;

public class DBMTMContactKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.Case_No
     *
     * @mbggenerated
     */
    private String caseNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.Serino
     *
     * @mbggenerated
     */
    private String serino;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MTMContact
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.Case_No
     *
     * @return the value of MTMContact.Case_No
     *
     * @mbggenerated
     */
    public String getCaseNo() {
        return caseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.Case_No
     *
     * @param caseNo the value for MTMContact.Case_No
     *
     * @mbggenerated
     */
    public void setCaseNo(String caseNo) {
        this.caseNo = caseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.Serino
     *
     * @return the value of MTMContact.Serino
     *
     * @mbggenerated
     */
    public String getSerino() {
        return serino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.Serino
     *
     * @param serino the value for MTMContact.Serino
     *
     * @mbggenerated
     */
    public void setSerino(String serino) {
        this.serino = serino;
    }
}