package mybatis.two.po;

import java.io.Serializable;
import java.util.Date;

public class DBMTMContact extends DBMTMContactKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.AddrC
     *
     * @mbggenerated
     */
    private String addrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.PKind
     *
     * @mbggenerated
     */
    private String pkind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.PRelation
     *
     * @mbggenerated
     */
    private String prelation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.PName
     *
     * @mbggenerated
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.PTitle
     *
     * @mbggenerated
     */
    private String ptitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.PID
     *
     * @mbggenerated
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.Sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.PBirthDay
     *
     * @mbggenerated
     */
    private Date pbirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.OfficeTitle
     *
     * @mbggenerated
     */
    private String officetitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.PTelCode
     *
     * @mbggenerated
     */
    private String ptelcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.PTel
     *
     * @mbggenerated
     */
    private String ptel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.TelCK
     *
     * @mbggenerated
     */
    private String telck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.TelRes
     *
     * @mbggenerated
     */
    private String telres;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.PTel1Code
     *
     * @mbggenerated
     */
    private String ptel1code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.PTel1
     *
     * @mbggenerated
     */
    private String ptel1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.Tel1CK
     *
     * @mbggenerated
     */
    private String tel1ck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.Tel1Res
     *
     * @mbggenerated
     */
    private String tel1res;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.OtherMail
     *
     * @mbggenerated
     */
    private String othermail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.PAddr
     *
     * @mbggenerated
     */
    private String paddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.AddCK
     *
     * @mbggenerated
     */
    private String addck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.AddRes
     *
     * @mbggenerated
     */
    private String addres;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.Email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.KyUser
     *
     * @mbggenerated
     */
    private String kyuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.KyDate
     *
     * @mbggenerated
     */
    private Date kydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.UpCDate
     *
     * @mbggenerated
     */
    private Date upcdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.UpUser
     *
     * @mbggenerated
     */
    private String upuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.Pstate
     *
     * @mbggenerated
     */
    private String pstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.AsSendAddr
     *
     * @mbggenerated
     */
    private String assendaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTMContact.rowguid
     *
     * @mbggenerated
     */
    private String rowguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MTMContact
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.AddrC
     *
     * @return the value of MTMContact.AddrC
     *
     * @mbggenerated
     */
    public String getAddrc() {
        return addrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.AddrC
     *
     * @param addrc the value for MTMContact.AddrC
     *
     * @mbggenerated
     */
    public void setAddrc(String addrc) {
        this.addrc = addrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.PKind
     *
     * @return the value of MTMContact.PKind
     *
     * @mbggenerated
     */
    public String getPkind() {
        return pkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.PKind
     *
     * @param pkind the value for MTMContact.PKind
     *
     * @mbggenerated
     */
    public void setPkind(String pkind) {
        this.pkind = pkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.PRelation
     *
     * @return the value of MTMContact.PRelation
     *
     * @mbggenerated
     */
    public String getPrelation() {
        return prelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.PRelation
     *
     * @param prelation the value for MTMContact.PRelation
     *
     * @mbggenerated
     */
    public void setPrelation(String prelation) {
        this.prelation = prelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.PName
     *
     * @return the value of MTMContact.PName
     *
     * @mbggenerated
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.PName
     *
     * @param pname the value for MTMContact.PName
     *
     * @mbggenerated
     */
    public void setPname(String pname) {
        this.pname = pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.PTitle
     *
     * @return the value of MTMContact.PTitle
     *
     * @mbggenerated
     */
    public String getPtitle() {
        return ptitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.PTitle
     *
     * @param ptitle the value for MTMContact.PTitle
     *
     * @mbggenerated
     */
    public void setPtitle(String ptitle) {
        this.ptitle = ptitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.PID
     *
     * @return the value of MTMContact.PID
     *
     * @mbggenerated
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.PID
     *
     * @param pid the value for MTMContact.PID
     *
     * @mbggenerated
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.Sex
     *
     * @return the value of MTMContact.Sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.Sex
     *
     * @param sex the value for MTMContact.Sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.PBirthDay
     *
     * @return the value of MTMContact.PBirthDay
     *
     * @mbggenerated
     */
    public Date getPbirthday() {
        return pbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.PBirthDay
     *
     * @param pbirthday the value for MTMContact.PBirthDay
     *
     * @mbggenerated
     */
    public void setPbirthday(Date pbirthday) {
        this.pbirthday = pbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.OfficeTitle
     *
     * @return the value of MTMContact.OfficeTitle
     *
     * @mbggenerated
     */
    public String getOfficetitle() {
        return officetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.OfficeTitle
     *
     * @param officetitle the value for MTMContact.OfficeTitle
     *
     * @mbggenerated
     */
    public void setOfficetitle(String officetitle) {
        this.officetitle = officetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.PTelCode
     *
     * @return the value of MTMContact.PTelCode
     *
     * @mbggenerated
     */
    public String getPtelcode() {
        return ptelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.PTelCode
     *
     * @param ptelcode the value for MTMContact.PTelCode
     *
     * @mbggenerated
     */
    public void setPtelcode(String ptelcode) {
        this.ptelcode = ptelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.PTel
     *
     * @return the value of MTMContact.PTel
     *
     * @mbggenerated
     */
    public String getPtel() {
        return ptel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.PTel
     *
     * @param ptel the value for MTMContact.PTel
     *
     * @mbggenerated
     */
    public void setPtel(String ptel) {
        this.ptel = ptel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.TelCK
     *
     * @return the value of MTMContact.TelCK
     *
     * @mbggenerated
     */
    public String getTelck() {
        return telck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.TelCK
     *
     * @param telck the value for MTMContact.TelCK
     *
     * @mbggenerated
     */
    public void setTelck(String telck) {
        this.telck = telck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.TelRes
     *
     * @return the value of MTMContact.TelRes
     *
     * @mbggenerated
     */
    public String getTelres() {
        return telres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.TelRes
     *
     * @param telres the value for MTMContact.TelRes
     *
     * @mbggenerated
     */
    public void setTelres(String telres) {
        this.telres = telres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.PTel1Code
     *
     * @return the value of MTMContact.PTel1Code
     *
     * @mbggenerated
     */
    public String getPtel1code() {
        return ptel1code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.PTel1Code
     *
     * @param ptel1code the value for MTMContact.PTel1Code
     *
     * @mbggenerated
     */
    public void setPtel1code(String ptel1code) {
        this.ptel1code = ptel1code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.PTel1
     *
     * @return the value of MTMContact.PTel1
     *
     * @mbggenerated
     */
    public String getPtel1() {
        return ptel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.PTel1
     *
     * @param ptel1 the value for MTMContact.PTel1
     *
     * @mbggenerated
     */
    public void setPtel1(String ptel1) {
        this.ptel1 = ptel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.Tel1CK
     *
     * @return the value of MTMContact.Tel1CK
     *
     * @mbggenerated
     */
    public String getTel1ck() {
        return tel1ck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.Tel1CK
     *
     * @param tel1ck the value for MTMContact.Tel1CK
     *
     * @mbggenerated
     */
    public void setTel1ck(String tel1ck) {
        this.tel1ck = tel1ck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.Tel1Res
     *
     * @return the value of MTMContact.Tel1Res
     *
     * @mbggenerated
     */
    public String getTel1res() {
        return tel1res;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.Tel1Res
     *
     * @param tel1res the value for MTMContact.Tel1Res
     *
     * @mbggenerated
     */
    public void setTel1res(String tel1res) {
        this.tel1res = tel1res;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.OtherMail
     *
     * @return the value of MTMContact.OtherMail
     *
     * @mbggenerated
     */
    public String getOthermail() {
        return othermail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.OtherMail
     *
     * @param othermail the value for MTMContact.OtherMail
     *
     * @mbggenerated
     */
    public void setOthermail(String othermail) {
        this.othermail = othermail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.PAddr
     *
     * @return the value of MTMContact.PAddr
     *
     * @mbggenerated
     */
    public String getPaddr() {
        return paddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.PAddr
     *
     * @param paddr the value for MTMContact.PAddr
     *
     * @mbggenerated
     */
    public void setPaddr(String paddr) {
        this.paddr = paddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.AddCK
     *
     * @return the value of MTMContact.AddCK
     *
     * @mbggenerated
     */
    public String getAddck() {
        return addck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.AddCK
     *
     * @param addck the value for MTMContact.AddCK
     *
     * @mbggenerated
     */
    public void setAddck(String addck) {
        this.addck = addck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.AddRes
     *
     * @return the value of MTMContact.AddRes
     *
     * @mbggenerated
     */
    public String getAddres() {
        return addres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.AddRes
     *
     * @param addres the value for MTMContact.AddRes
     *
     * @mbggenerated
     */
    public void setAddres(String addres) {
        this.addres = addres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.Email
     *
     * @return the value of MTMContact.Email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.Email
     *
     * @param email the value for MTMContact.Email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.KyUser
     *
     * @return the value of MTMContact.KyUser
     *
     * @mbggenerated
     */
    public String getKyuser() {
        return kyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.KyUser
     *
     * @param kyuser the value for MTMContact.KyUser
     *
     * @mbggenerated
     */
    public void setKyuser(String kyuser) {
        this.kyuser = kyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.KyDate
     *
     * @return the value of MTMContact.KyDate
     *
     * @mbggenerated
     */
    public Date getKydate() {
        return kydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.KyDate
     *
     * @param kydate the value for MTMContact.KyDate
     *
     * @mbggenerated
     */
    public void setKydate(Date kydate) {
        this.kydate = kydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.UpCDate
     *
     * @return the value of MTMContact.UpCDate
     *
     * @mbggenerated
     */
    public Date getUpcdate() {
        return upcdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.UpCDate
     *
     * @param upcdate the value for MTMContact.UpCDate
     *
     * @mbggenerated
     */
    public void setUpcdate(Date upcdate) {
        this.upcdate = upcdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.UpUser
     *
     * @return the value of MTMContact.UpUser
     *
     * @mbggenerated
     */
    public String getUpuser() {
        return upuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.UpUser
     *
     * @param upuser the value for MTMContact.UpUser
     *
     * @mbggenerated
     */
    public void setUpuser(String upuser) {
        this.upuser = upuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.Pstate
     *
     * @return the value of MTMContact.Pstate
     *
     * @mbggenerated
     */
    public String getPstate() {
        return pstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.Pstate
     *
     * @param pstate the value for MTMContact.Pstate
     *
     * @mbggenerated
     */
    public void setPstate(String pstate) {
        this.pstate = pstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.AsSendAddr
     *
     * @return the value of MTMContact.AsSendAddr
     *
     * @mbggenerated
     */
    public String getAssendaddr() {
        return assendaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.AsSendAddr
     *
     * @param assendaddr the value for MTMContact.AsSendAddr
     *
     * @mbggenerated
     */
    public void setAssendaddr(String assendaddr) {
        this.assendaddr = assendaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTMContact.rowguid
     *
     * @return the value of MTMContact.rowguid
     *
     * @mbggenerated
     */
    public String getRowguid() {
        return rowguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTMContact.rowguid
     *
     * @param rowguid the value for MTMContact.rowguid
     *
     * @mbggenerated
     */
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }
}