package mybatis.two.po;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DBMTMCaseDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MTMCaseData
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MTMCaseData
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MTMCaseData
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTMCaseData
     *
     * @mbggenerated
     */
    public DBMTMCaseDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTMCaseData
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTMCaseData
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTMCaseData
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTMCaseData
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTMCaseData
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTMCaseData
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTMCaseData
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTMCaseData
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTMCaseData
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTMCaseData
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MTMCaseData
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCaseNoIsNull() {
            addCriterion("Case_No is null");
            return (Criteria) this;
        }

        public Criteria andCaseNoIsNotNull() {
            addCriterion("Case_No is not null");
            return (Criteria) this;
        }

        public Criteria andCaseNoEqualTo(String value) {
            addCriterion("Case_No =", value, "caseNo");
            return (Criteria) this;
        }

        public Criteria andCaseNoNotEqualTo(String value) {
            addCriterion("Case_No <>", value, "caseNo");
            return (Criteria) this;
        }

        public Criteria andCaseNoGreaterThan(String value) {
            addCriterion("Case_No >", value, "caseNo");
            return (Criteria) this;
        }

        public Criteria andCaseNoGreaterThanOrEqualTo(String value) {
            addCriterion("Case_No >=", value, "caseNo");
            return (Criteria) this;
        }

        public Criteria andCaseNoLessThan(String value) {
            addCriterion("Case_No <", value, "caseNo");
            return (Criteria) this;
        }

        public Criteria andCaseNoLessThanOrEqualTo(String value) {
            addCriterion("Case_No <=", value, "caseNo");
            return (Criteria) this;
        }

        public Criteria andCaseNoLike(String value) {
            addCriterion("Case_No like", value, "caseNo");
            return (Criteria) this;
        }

        public Criteria andCaseNoNotLike(String value) {
            addCriterion("Case_No not like", value, "caseNo");
            return (Criteria) this;
        }

        public Criteria andCaseNoIn(List<String> values) {
            addCriterion("Case_No in", values, "caseNo");
            return (Criteria) this;
        }

        public Criteria andCaseNoNotIn(List<String> values) {
            addCriterion("Case_No not in", values, "caseNo");
            return (Criteria) this;
        }

        public Criteria andCaseNoBetween(String value1, String value2) {
            addCriterion("Case_No between", value1, value2, "caseNo");
            return (Criteria) this;
        }

        public Criteria andCaseNoNotBetween(String value1, String value2) {
            addCriterion("Case_No not between", value1, value2, "caseNo");
            return (Criteria) this;
        }

        public Criteria andCoNoIsNull() {
            addCriterion("Co_No is null");
            return (Criteria) this;
        }

        public Criteria andCoNoIsNotNull() {
            addCriterion("Co_No is not null");
            return (Criteria) this;
        }

        public Criteria andCoNoEqualTo(String value) {
            addCriterion("Co_No =", value, "coNo");
            return (Criteria) this;
        }

        public Criteria andCoNoNotEqualTo(String value) {
            addCriterion("Co_No <>", value, "coNo");
            return (Criteria) this;
        }

        public Criteria andCoNoGreaterThan(String value) {
            addCriterion("Co_No >", value, "coNo");
            return (Criteria) this;
        }

        public Criteria andCoNoGreaterThanOrEqualTo(String value) {
            addCriterion("Co_No >=", value, "coNo");
            return (Criteria) this;
        }

        public Criteria andCoNoLessThan(String value) {
            addCriterion("Co_No <", value, "coNo");
            return (Criteria) this;
        }

        public Criteria andCoNoLessThanOrEqualTo(String value) {
            addCriterion("Co_No <=", value, "coNo");
            return (Criteria) this;
        }

        public Criteria andCoNoLike(String value) {
            addCriterion("Co_No like", value, "coNo");
            return (Criteria) this;
        }

        public Criteria andCoNoNotLike(String value) {
            addCriterion("Co_No not like", value, "coNo");
            return (Criteria) this;
        }

        public Criteria andCoNoIn(List<String> values) {
            addCriterion("Co_No in", values, "coNo");
            return (Criteria) this;
        }

        public Criteria andCoNoNotIn(List<String> values) {
            addCriterion("Co_No not in", values, "coNo");
            return (Criteria) this;
        }

        public Criteria andCoNoBetween(String value1, String value2) {
            addCriterion("Co_No between", value1, value2, "coNo");
            return (Criteria) this;
        }

        public Criteria andCoNoNotBetween(String value1, String value2) {
            addCriterion("Co_No not between", value1, value2, "coNo");
            return (Criteria) this;
        }

        public Criteria andItemnoIsNull() {
            addCriterion("ItemNo is null");
            return (Criteria) this;
        }

        public Criteria andItemnoIsNotNull() {
            addCriterion("ItemNo is not null");
            return (Criteria) this;
        }

        public Criteria andItemnoEqualTo(String value) {
            addCriterion("ItemNo =", value, "itemno");
            return (Criteria) this;
        }

        public Criteria andItemnoNotEqualTo(String value) {
            addCriterion("ItemNo <>", value, "itemno");
            return (Criteria) this;
        }

        public Criteria andItemnoGreaterThan(String value) {
            addCriterion("ItemNo >", value, "itemno");
            return (Criteria) this;
        }

        public Criteria andItemnoGreaterThanOrEqualTo(String value) {
            addCriterion("ItemNo >=", value, "itemno");
            return (Criteria) this;
        }

        public Criteria andItemnoLessThan(String value) {
            addCriterion("ItemNo <", value, "itemno");
            return (Criteria) this;
        }

        public Criteria andItemnoLessThanOrEqualTo(String value) {
            addCriterion("ItemNo <=", value, "itemno");
            return (Criteria) this;
        }

        public Criteria andItemnoLike(String value) {
            addCriterion("ItemNo like", value, "itemno");
            return (Criteria) this;
        }

        public Criteria andItemnoNotLike(String value) {
            addCriterion("ItemNo not like", value, "itemno");
            return (Criteria) this;
        }

        public Criteria andItemnoIn(List<String> values) {
            addCriterion("ItemNo in", values, "itemno");
            return (Criteria) this;
        }

        public Criteria andItemnoNotIn(List<String> values) {
            addCriterion("ItemNo not in", values, "itemno");
            return (Criteria) this;
        }

        public Criteria andItemnoBetween(String value1, String value2) {
            addCriterion("ItemNo between", value1, value2, "itemno");
            return (Criteria) this;
        }

        public Criteria andItemnoNotBetween(String value1, String value2) {
            addCriterion("ItemNo not between", value1, value2, "itemno");
            return (Criteria) this;
        }

        public Criteria andBatnumIsNull() {
            addCriterion("BatNum is null");
            return (Criteria) this;
        }

        public Criteria andBatnumIsNotNull() {
            addCriterion("BatNum is not null");
            return (Criteria) this;
        }

        public Criteria andBatnumEqualTo(String value) {
            addCriterion("BatNum =", value, "batnum");
            return (Criteria) this;
        }

        public Criteria andBatnumNotEqualTo(String value) {
            addCriterion("BatNum <>", value, "batnum");
            return (Criteria) this;
        }

        public Criteria andBatnumGreaterThan(String value) {
            addCriterion("BatNum >", value, "batnum");
            return (Criteria) this;
        }

        public Criteria andBatnumGreaterThanOrEqualTo(String value) {
            addCriterion("BatNum >=", value, "batnum");
            return (Criteria) this;
        }

        public Criteria andBatnumLessThan(String value) {
            addCriterion("BatNum <", value, "batnum");
            return (Criteria) this;
        }

        public Criteria andBatnumLessThanOrEqualTo(String value) {
            addCriterion("BatNum <=", value, "batnum");
            return (Criteria) this;
        }

        public Criteria andBatnumLike(String value) {
            addCriterion("BatNum like", value, "batnum");
            return (Criteria) this;
        }

        public Criteria andBatnumNotLike(String value) {
            addCriterion("BatNum not like", value, "batnum");
            return (Criteria) this;
        }

        public Criteria andBatnumIn(List<String> values) {
            addCriterion("BatNum in", values, "batnum");
            return (Criteria) this;
        }

        public Criteria andBatnumNotIn(List<String> values) {
            addCriterion("BatNum not in", values, "batnum");
            return (Criteria) this;
        }

        public Criteria andBatnumBetween(String value1, String value2) {
            addCriterion("BatNum between", value1, value2, "batnum");
            return (Criteria) this;
        }

        public Criteria andBatnumNotBetween(String value1, String value2) {
            addCriterion("BatNum not between", value1, value2, "batnum");
            return (Criteria) this;
        }

        public Criteria andCaseDateIsNull() {
            addCriterion("Case_Date is null");
            return (Criteria) this;
        }

        public Criteria andCaseDateIsNotNull() {
            addCriterion("Case_Date is not null");
            return (Criteria) this;
        }

        public Criteria andCaseDateEqualTo(Date value) {
            addCriterion("Case_Date =", value, "caseDate");
            return (Criteria) this;
        }

        public Criteria andCaseDateNotEqualTo(Date value) {
            addCriterion("Case_Date <>", value, "caseDate");
            return (Criteria) this;
        }

        public Criteria andCaseDateGreaterThan(Date value) {
            addCriterion("Case_Date >", value, "caseDate");
            return (Criteria) this;
        }

        public Criteria andCaseDateGreaterThanOrEqualTo(Date value) {
            addCriterion("Case_Date >=", value, "caseDate");
            return (Criteria) this;
        }

        public Criteria andCaseDateLessThan(Date value) {
            addCriterion("Case_Date <", value, "caseDate");
            return (Criteria) this;
        }

        public Criteria andCaseDateLessThanOrEqualTo(Date value) {
            addCriterion("Case_Date <=", value, "caseDate");
            return (Criteria) this;
        }

        public Criteria andCaseDateIn(List<Date> values) {
            addCriterion("Case_Date in", values, "caseDate");
            return (Criteria) this;
        }

        public Criteria andCaseDateNotIn(List<Date> values) {
            addCriterion("Case_Date not in", values, "caseDate");
            return (Criteria) this;
        }

        public Criteria andCaseDateBetween(Date value1, Date value2) {
            addCriterion("Case_Date between", value1, value2, "caseDate");
            return (Criteria) this;
        }

        public Criteria andCaseDateNotBetween(Date value1, Date value2) {
            addCriterion("Case_Date not between", value1, value2, "caseDate");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIsNull() {
            addCriterion("Case_Type is null");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIsNotNull() {
            addCriterion("Case_Type is not null");
            return (Criteria) this;
        }

        public Criteria andCaseTypeEqualTo(String value) {
            addCriterion("Case_Type =", value, "caseType");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNotEqualTo(String value) {
            addCriterion("Case_Type <>", value, "caseType");
            return (Criteria) this;
        }

        public Criteria andCaseTypeGreaterThan(String value) {
            addCriterion("Case_Type >", value, "caseType");
            return (Criteria) this;
        }

        public Criteria andCaseTypeGreaterThanOrEqualTo(String value) {
            addCriterion("Case_Type >=", value, "caseType");
            return (Criteria) this;
        }

        public Criteria andCaseTypeLessThan(String value) {
            addCriterion("Case_Type <", value, "caseType");
            return (Criteria) this;
        }

        public Criteria andCaseTypeLessThanOrEqualTo(String value) {
            addCriterion("Case_Type <=", value, "caseType");
            return (Criteria) this;
        }

        public Criteria andCaseTypeLike(String value) {
            addCriterion("Case_Type like", value, "caseType");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNotLike(String value) {
            addCriterion("Case_Type not like", value, "caseType");
            return (Criteria) this;
        }

        public Criteria andCaseTypeIn(List<String> values) {
            addCriterion("Case_Type in", values, "caseType");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNotIn(List<String> values) {
            addCriterion("Case_Type not in", values, "caseType");
            return (Criteria) this;
        }

        public Criteria andCaseTypeBetween(String value1, String value2) {
            addCriterion("Case_Type between", value1, value2, "caseType");
            return (Criteria) this;
        }

        public Criteria andCaseTypeNotBetween(String value1, String value2) {
            addCriterion("Case_Type not between", value1, value2, "caseType");
            return (Criteria) this;
        }

        public Criteria andCateNoIsNull() {
            addCriterion("Cate_No is null");
            return (Criteria) this;
        }

        public Criteria andCateNoIsNotNull() {
            addCriterion("Cate_No is not null");
            return (Criteria) this;
        }

        public Criteria andCateNoEqualTo(String value) {
            addCriterion("Cate_No =", value, "cateNo");
            return (Criteria) this;
        }

        public Criteria andCateNoNotEqualTo(String value) {
            addCriterion("Cate_No <>", value, "cateNo");
            return (Criteria) this;
        }

        public Criteria andCateNoGreaterThan(String value) {
            addCriterion("Cate_No >", value, "cateNo");
            return (Criteria) this;
        }

        public Criteria andCateNoGreaterThanOrEqualTo(String value) {
            addCriterion("Cate_No >=", value, "cateNo");
            return (Criteria) this;
        }

        public Criteria andCateNoLessThan(String value) {
            addCriterion("Cate_No <", value, "cateNo");
            return (Criteria) this;
        }

        public Criteria andCateNoLessThanOrEqualTo(String value) {
            addCriterion("Cate_No <=", value, "cateNo");
            return (Criteria) this;
        }

        public Criteria andCateNoLike(String value) {
            addCriterion("Cate_No like", value, "cateNo");
            return (Criteria) this;
        }

        public Criteria andCateNoNotLike(String value) {
            addCriterion("Cate_No not like", value, "cateNo");
            return (Criteria) this;
        }

        public Criteria andCateNoIn(List<String> values) {
            addCriterion("Cate_No in", values, "cateNo");
            return (Criteria) this;
        }

        public Criteria andCateNoNotIn(List<String> values) {
            addCriterion("Cate_No not in", values, "cateNo");
            return (Criteria) this;
        }

        public Criteria andCateNoBetween(String value1, String value2) {
            addCriterion("Cate_No between", value1, value2, "cateNo");
            return (Criteria) this;
        }

        public Criteria andCateNoNotBetween(String value1, String value2) {
            addCriterion("Cate_No not between", value1, value2, "cateNo");
            return (Criteria) this;
        }

        public Criteria andPnameIsNull() {
            addCriterion("PName is null");
            return (Criteria) this;
        }

        public Criteria andPnameIsNotNull() {
            addCriterion("PName is not null");
            return (Criteria) this;
        }

        public Criteria andPnameEqualTo(String value) {
            addCriterion("PName =", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameNotEqualTo(String value) {
            addCriterion("PName <>", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameGreaterThan(String value) {
            addCriterion("PName >", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameGreaterThanOrEqualTo(String value) {
            addCriterion("PName >=", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameLessThan(String value) {
            addCriterion("PName <", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameLessThanOrEqualTo(String value) {
            addCriterion("PName <=", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameLike(String value) {
            addCriterion("PName like", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameNotLike(String value) {
            addCriterion("PName not like", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameIn(List<String> values) {
            addCriterion("PName in", values, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameNotIn(List<String> values) {
            addCriterion("PName not in", values, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameBetween(String value1, String value2) {
            addCriterion("PName between", value1, value2, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameNotBetween(String value1, String value2) {
            addCriterion("PName not between", value1, value2, "pname");
            return (Criteria) this;
        }

        public Criteria andPidIsNull() {
            addCriterion("PID is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("PID is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(String value) {
            addCriterion("PID =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(String value) {
            addCriterion("PID <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(String value) {
            addCriterion("PID >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(String value) {
            addCriterion("PID >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(String value) {
            addCriterion("PID <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(String value) {
            addCriterion("PID <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLike(String value) {
            addCriterion("PID like", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotLike(String value) {
            addCriterion("PID not like", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<String> values) {
            addCriterion("PID in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<String> values) {
            addCriterion("PID not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(String value1, String value2) {
            addCriterion("PID between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(String value1, String value2) {
            addCriterion("PID not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andBirthIsNull() {
            addCriterion("Birth is null");
            return (Criteria) this;
        }

        public Criteria andBirthIsNotNull() {
            addCriterion("Birth is not null");
            return (Criteria) this;
        }

        public Criteria andBirthEqualTo(Date value) {
            addCriterion("Birth =", value, "birth");
            return (Criteria) this;
        }

        public Criteria andBirthNotEqualTo(Date value) {
            addCriterion("Birth <>", value, "birth");
            return (Criteria) this;
        }

        public Criteria andBirthGreaterThan(Date value) {
            addCriterion("Birth >", value, "birth");
            return (Criteria) this;
        }

        public Criteria andBirthGreaterThanOrEqualTo(Date value) {
            addCriterion("Birth >=", value, "birth");
            return (Criteria) this;
        }

        public Criteria andBirthLessThan(Date value) {
            addCriterion("Birth <", value, "birth");
            return (Criteria) this;
        }

        public Criteria andBirthLessThanOrEqualTo(Date value) {
            addCriterion("Birth <=", value, "birth");
            return (Criteria) this;
        }

        public Criteria andBirthIn(List<Date> values) {
            addCriterion("Birth in", values, "birth");
            return (Criteria) this;
        }

        public Criteria andBirthNotIn(List<Date> values) {
            addCriterion("Birth not in", values, "birth");
            return (Criteria) this;
        }

        public Criteria andBirthBetween(Date value1, Date value2) {
            addCriterion("Birth between", value1, value2, "birth");
            return (Criteria) this;
        }

        public Criteria andBirthNotBetween(Date value1, Date value2) {
            addCriterion("Birth not between", value1, value2, "birth");
            return (Criteria) this;
        }

        public Criteria andRemIsNull() {
            addCriterion("Rem is null");
            return (Criteria) this;
        }

        public Criteria andRemIsNotNull() {
            addCriterion("Rem is not null");
            return (Criteria) this;
        }

        public Criteria andRemEqualTo(String value) {
            addCriterion("Rem =", value, "rem");
            return (Criteria) this;
        }

        public Criteria andRemNotEqualTo(String value) {
            addCriterion("Rem <>", value, "rem");
            return (Criteria) this;
        }

        public Criteria andRemGreaterThan(String value) {
            addCriterion("Rem >", value, "rem");
            return (Criteria) this;
        }

        public Criteria andRemGreaterThanOrEqualTo(String value) {
            addCriterion("Rem >=", value, "rem");
            return (Criteria) this;
        }

        public Criteria andRemLessThan(String value) {
            addCriterion("Rem <", value, "rem");
            return (Criteria) this;
        }

        public Criteria andRemLessThanOrEqualTo(String value) {
            addCriterion("Rem <=", value, "rem");
            return (Criteria) this;
        }

        public Criteria andRemLike(String value) {
            addCriterion("Rem like", value, "rem");
            return (Criteria) this;
        }

        public Criteria andRemNotLike(String value) {
            addCriterion("Rem not like", value, "rem");
            return (Criteria) this;
        }

        public Criteria andRemIn(List<String> values) {
            addCriterion("Rem in", values, "rem");
            return (Criteria) this;
        }

        public Criteria andRemNotIn(List<String> values) {
            addCriterion("Rem not in", values, "rem");
            return (Criteria) this;
        }

        public Criteria andRemBetween(String value1, String value2) {
            addCriterion("Rem between", value1, value2, "rem");
            return (Criteria) this;
        }

        public Criteria andRemNotBetween(String value1, String value2) {
            addCriterion("Rem not between", value1, value2, "rem");
            return (Criteria) this;
        }

        public Criteria andIncomenoIsNull() {
            addCriterion("IncomeNo is null");
            return (Criteria) this;
        }

        public Criteria andIncomenoIsNotNull() {
            addCriterion("IncomeNo is not null");
            return (Criteria) this;
        }

        public Criteria andIncomenoEqualTo(String value) {
            addCriterion("IncomeNo =", value, "incomeno");
            return (Criteria) this;
        }

        public Criteria andIncomenoNotEqualTo(String value) {
            addCriterion("IncomeNo <>", value, "incomeno");
            return (Criteria) this;
        }

        public Criteria andIncomenoGreaterThan(String value) {
            addCriterion("IncomeNo >", value, "incomeno");
            return (Criteria) this;
        }

        public Criteria andIncomenoGreaterThanOrEqualTo(String value) {
            addCriterion("IncomeNo >=", value, "incomeno");
            return (Criteria) this;
        }

        public Criteria andIncomenoLessThan(String value) {
            addCriterion("IncomeNo <", value, "incomeno");
            return (Criteria) this;
        }

        public Criteria andIncomenoLessThanOrEqualTo(String value) {
            addCriterion("IncomeNo <=", value, "incomeno");
            return (Criteria) this;
        }

        public Criteria andIncomenoLike(String value) {
            addCriterion("IncomeNo like", value, "incomeno");
            return (Criteria) this;
        }

        public Criteria andIncomenoNotLike(String value) {
            addCriterion("IncomeNo not like", value, "incomeno");
            return (Criteria) this;
        }

        public Criteria andIncomenoIn(List<String> values) {
            addCriterion("IncomeNo in", values, "incomeno");
            return (Criteria) this;
        }

        public Criteria andIncomenoNotIn(List<String> values) {
            addCriterion("IncomeNo not in", values, "incomeno");
            return (Criteria) this;
        }

        public Criteria andIncomenoBetween(String value1, String value2) {
            addCriterion("IncomeNo between", value1, value2, "incomeno");
            return (Criteria) this;
        }

        public Criteria andIncomenoNotBetween(String value1, String value2) {
            addCriterion("IncomeNo not between", value1, value2, "incomeno");
            return (Criteria) this;
        }

        public Criteria andNextdateIsNull() {
            addCriterion("NextDate is null");
            return (Criteria) this;
        }

        public Criteria andNextdateIsNotNull() {
            addCriterion("NextDate is not null");
            return (Criteria) this;
        }

        public Criteria andNextdateEqualTo(Date value) {
            addCriterion("NextDate =", value, "nextdate");
            return (Criteria) this;
        }

        public Criteria andNextdateNotEqualTo(Date value) {
            addCriterion("NextDate <>", value, "nextdate");
            return (Criteria) this;
        }

        public Criteria andNextdateGreaterThan(Date value) {
            addCriterion("NextDate >", value, "nextdate");
            return (Criteria) this;
        }

        public Criteria andNextdateGreaterThanOrEqualTo(Date value) {
            addCriterion("NextDate >=", value, "nextdate");
            return (Criteria) this;
        }

        public Criteria andNextdateLessThan(Date value) {
            addCriterion("NextDate <", value, "nextdate");
            return (Criteria) this;
        }

        public Criteria andNextdateLessThanOrEqualTo(Date value) {
            addCriterion("NextDate <=", value, "nextdate");
            return (Criteria) this;
        }

        public Criteria andNextdateIn(List<Date> values) {
            addCriterion("NextDate in", values, "nextdate");
            return (Criteria) this;
        }

        public Criteria andNextdateNotIn(List<Date> values) {
            addCriterion("NextDate not in", values, "nextdate");
            return (Criteria) this;
        }

        public Criteria andNextdateBetween(Date value1, Date value2) {
            addCriterion("NextDate between", value1, value2, "nextdate");
            return (Criteria) this;
        }

        public Criteria andNextdateNotBetween(Date value1, Date value2) {
            addCriterion("NextDate not between", value1, value2, "nextdate");
            return (Criteria) this;
        }

        public Criteria andRetdateIsNull() {
            addCriterion("RetDate is null");
            return (Criteria) this;
        }

        public Criteria andRetdateIsNotNull() {
            addCriterion("RetDate is not null");
            return (Criteria) this;
        }

        public Criteria andRetdateEqualTo(Date value) {
            addCriterion("RetDate =", value, "retdate");
            return (Criteria) this;
        }

        public Criteria andRetdateNotEqualTo(Date value) {
            addCriterion("RetDate <>", value, "retdate");
            return (Criteria) this;
        }

        public Criteria andRetdateGreaterThan(Date value) {
            addCriterion("RetDate >", value, "retdate");
            return (Criteria) this;
        }

        public Criteria andRetdateGreaterThanOrEqualTo(Date value) {
            addCriterion("RetDate >=", value, "retdate");
            return (Criteria) this;
        }

        public Criteria andRetdateLessThan(Date value) {
            addCriterion("RetDate <", value, "retdate");
            return (Criteria) this;
        }

        public Criteria andRetdateLessThanOrEqualTo(Date value) {
            addCriterion("RetDate <=", value, "retdate");
            return (Criteria) this;
        }

        public Criteria andRetdateIn(List<Date> values) {
            addCriterion("RetDate in", values, "retdate");
            return (Criteria) this;
        }

        public Criteria andRetdateNotIn(List<Date> values) {
            addCriterion("RetDate not in", values, "retdate");
            return (Criteria) this;
        }

        public Criteria andRetdateBetween(Date value1, Date value2) {
            addCriterion("RetDate between", value1, value2, "retdate");
            return (Criteria) this;
        }

        public Criteria andRetdateNotBetween(Date value1, Date value2) {
            addCriterion("RetDate not between", value1, value2, "retdate");
            return (Criteria) this;
        }

        public Criteria andRetremIsNull() {
            addCriterion("RetRem is null");
            return (Criteria) this;
        }

        public Criteria andRetremIsNotNull() {
            addCriterion("RetRem is not null");
            return (Criteria) this;
        }

        public Criteria andRetremEqualTo(String value) {
            addCriterion("RetRem =", value, "retrem");
            return (Criteria) this;
        }

        public Criteria andRetremNotEqualTo(String value) {
            addCriterion("RetRem <>", value, "retrem");
            return (Criteria) this;
        }

        public Criteria andRetremGreaterThan(String value) {
            addCriterion("RetRem >", value, "retrem");
            return (Criteria) this;
        }

        public Criteria andRetremGreaterThanOrEqualTo(String value) {
            addCriterion("RetRem >=", value, "retrem");
            return (Criteria) this;
        }

        public Criteria andRetremLessThan(String value) {
            addCriterion("RetRem <", value, "retrem");
            return (Criteria) this;
        }

        public Criteria andRetremLessThanOrEqualTo(String value) {
            addCriterion("RetRem <=", value, "retrem");
            return (Criteria) this;
        }

        public Criteria andRetremLike(String value) {
            addCriterion("RetRem like", value, "retrem");
            return (Criteria) this;
        }

        public Criteria andRetremNotLike(String value) {
            addCriterion("RetRem not like", value, "retrem");
            return (Criteria) this;
        }

        public Criteria andRetremIn(List<String> values) {
            addCriterion("RetRem in", values, "retrem");
            return (Criteria) this;
        }

        public Criteria andRetremNotIn(List<String> values) {
            addCriterion("RetRem not in", values, "retrem");
            return (Criteria) this;
        }

        public Criteria andRetremBetween(String value1, String value2) {
            addCriterion("RetRem between", value1, value2, "retrem");
            return (Criteria) this;
        }

        public Criteria andRetremNotBetween(String value1, String value2) {
            addCriterion("RetRem not between", value1, value2, "retrem");
            return (Criteria) this;
        }

        public Criteria andRem1IsNull() {
            addCriterion("Rem1 is null");
            return (Criteria) this;
        }

        public Criteria andRem1IsNotNull() {
            addCriterion("Rem1 is not null");
            return (Criteria) this;
        }

        public Criteria andRem1EqualTo(String value) {
            addCriterion("Rem1 =", value, "rem1");
            return (Criteria) this;
        }

        public Criteria andRem1NotEqualTo(String value) {
            addCriterion("Rem1 <>", value, "rem1");
            return (Criteria) this;
        }

        public Criteria andRem1GreaterThan(String value) {
            addCriterion("Rem1 >", value, "rem1");
            return (Criteria) this;
        }

        public Criteria andRem1GreaterThanOrEqualTo(String value) {
            addCriterion("Rem1 >=", value, "rem1");
            return (Criteria) this;
        }

        public Criteria andRem1LessThan(String value) {
            addCriterion("Rem1 <", value, "rem1");
            return (Criteria) this;
        }

        public Criteria andRem1LessThanOrEqualTo(String value) {
            addCriterion("Rem1 <=", value, "rem1");
            return (Criteria) this;
        }

        public Criteria andRem1Like(String value) {
            addCriterion("Rem1 like", value, "rem1");
            return (Criteria) this;
        }

        public Criteria andRem1NotLike(String value) {
            addCriterion("Rem1 not like", value, "rem1");
            return (Criteria) this;
        }

        public Criteria andRem1In(List<String> values) {
            addCriterion("Rem1 in", values, "rem1");
            return (Criteria) this;
        }

        public Criteria andRem1NotIn(List<String> values) {
            addCriterion("Rem1 not in", values, "rem1");
            return (Criteria) this;
        }

        public Criteria andRem1Between(String value1, String value2) {
            addCriterion("Rem1 between", value1, value2, "rem1");
            return (Criteria) this;
        }

        public Criteria andRem1NotBetween(String value1, String value2) {
            addCriterion("Rem1 not between", value1, value2, "rem1");
            return (Criteria) this;
        }

        public Criteria andNotesIsNull() {
            addCriterion("Notes is null");
            return (Criteria) this;
        }

        public Criteria andNotesIsNotNull() {
            addCriterion("Notes is not null");
            return (Criteria) this;
        }

        public Criteria andNotesEqualTo(String value) {
            addCriterion("Notes =", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotEqualTo(String value) {
            addCriterion("Notes <>", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesGreaterThan(String value) {
            addCriterion("Notes >", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesGreaterThanOrEqualTo(String value) {
            addCriterion("Notes >=", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesLessThan(String value) {
            addCriterion("Notes <", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesLessThanOrEqualTo(String value) {
            addCriterion("Notes <=", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesLike(String value) {
            addCriterion("Notes like", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotLike(String value) {
            addCriterion("Notes not like", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesIn(List<String> values) {
            addCriterion("Notes in", values, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotIn(List<String> values) {
            addCriterion("Notes not in", values, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesBetween(String value1, String value2) {
            addCriterion("Notes between", value1, value2, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotBetween(String value1, String value2) {
            addCriterion("Notes not between", value1, value2, "notes");
            return (Criteria) this;
        }

        public Criteria andMflagIsNull() {
            addCriterion("MFlag is null");
            return (Criteria) this;
        }

        public Criteria andMflagIsNotNull() {
            addCriterion("MFlag is not null");
            return (Criteria) this;
        }

        public Criteria andMflagEqualTo(String value) {
            addCriterion("MFlag =", value, "mflag");
            return (Criteria) this;
        }

        public Criteria andMflagNotEqualTo(String value) {
            addCriterion("MFlag <>", value, "mflag");
            return (Criteria) this;
        }

        public Criteria andMflagGreaterThan(String value) {
            addCriterion("MFlag >", value, "mflag");
            return (Criteria) this;
        }

        public Criteria andMflagGreaterThanOrEqualTo(String value) {
            addCriterion("MFlag >=", value, "mflag");
            return (Criteria) this;
        }

        public Criteria andMflagLessThan(String value) {
            addCriterion("MFlag <", value, "mflag");
            return (Criteria) this;
        }

        public Criteria andMflagLessThanOrEqualTo(String value) {
            addCriterion("MFlag <=", value, "mflag");
            return (Criteria) this;
        }

        public Criteria andMflagLike(String value) {
            addCriterion("MFlag like", value, "mflag");
            return (Criteria) this;
        }

        public Criteria andMflagNotLike(String value) {
            addCriterion("MFlag not like", value, "mflag");
            return (Criteria) this;
        }

        public Criteria andMflagIn(List<String> values) {
            addCriterion("MFlag in", values, "mflag");
            return (Criteria) this;
        }

        public Criteria andMflagNotIn(List<String> values) {
            addCriterion("MFlag not in", values, "mflag");
            return (Criteria) this;
        }

        public Criteria andMflagBetween(String value1, String value2) {
            addCriterion("MFlag between", value1, value2, "mflag");
            return (Criteria) this;
        }

        public Criteria andMflagNotBetween(String value1, String value2) {
            addCriterion("MFlag not between", value1, value2, "mflag");
            return (Criteria) this;
        }

        public Criteria andReturndateIsNull() {
            addCriterion("ReturnDate is null");
            return (Criteria) this;
        }

        public Criteria andReturndateIsNotNull() {
            addCriterion("ReturnDate is not null");
            return (Criteria) this;
        }

        public Criteria andReturndateEqualTo(Date value) {
            addCriterion("ReturnDate =", value, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateNotEqualTo(Date value) {
            addCriterion("ReturnDate <>", value, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateGreaterThan(Date value) {
            addCriterion("ReturnDate >", value, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateGreaterThanOrEqualTo(Date value) {
            addCriterion("ReturnDate >=", value, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateLessThan(Date value) {
            addCriterion("ReturnDate <", value, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateLessThanOrEqualTo(Date value) {
            addCriterion("ReturnDate <=", value, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateIn(List<Date> values) {
            addCriterion("ReturnDate in", values, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateNotIn(List<Date> values) {
            addCriterion("ReturnDate not in", values, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateBetween(Date value1, Date value2) {
            addCriterion("ReturnDate between", value1, value2, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateNotBetween(Date value1, Date value2) {
            addCriterion("ReturnDate not between", value1, value2, "returndate");
            return (Criteria) this;
        }

        public Criteria andLastSontimeIsNull() {
            addCriterion("Last_SonTime is null");
            return (Criteria) this;
        }

        public Criteria andLastSontimeIsNotNull() {
            addCriterion("Last_SonTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastSontimeEqualTo(Date value) {
            addCriterion("Last_SonTime =", value, "lastSontime");
            return (Criteria) this;
        }

        public Criteria andLastSontimeNotEqualTo(Date value) {
            addCriterion("Last_SonTime <>", value, "lastSontime");
            return (Criteria) this;
        }

        public Criteria andLastSontimeGreaterThan(Date value) {
            addCriterion("Last_SonTime >", value, "lastSontime");
            return (Criteria) this;
        }

        public Criteria andLastSontimeGreaterThanOrEqualTo(Date value) {
            addCriterion("Last_SonTime >=", value, "lastSontime");
            return (Criteria) this;
        }

        public Criteria andLastSontimeLessThan(Date value) {
            addCriterion("Last_SonTime <", value, "lastSontime");
            return (Criteria) this;
        }

        public Criteria andLastSontimeLessThanOrEqualTo(Date value) {
            addCriterion("Last_SonTime <=", value, "lastSontime");
            return (Criteria) this;
        }

        public Criteria andLastSontimeIn(List<Date> values) {
            addCriterion("Last_SonTime in", values, "lastSontime");
            return (Criteria) this;
        }

        public Criteria andLastSontimeNotIn(List<Date> values) {
            addCriterion("Last_SonTime not in", values, "lastSontime");
            return (Criteria) this;
        }

        public Criteria andLastSontimeBetween(Date value1, Date value2) {
            addCriterion("Last_SonTime between", value1, value2, "lastSontime");
            return (Criteria) this;
        }

        public Criteria andLastSontimeNotBetween(Date value1, Date value2) {
            addCriterion("Last_SonTime not between", value1, value2, "lastSontime");
            return (Criteria) this;
        }

        public Criteria andLastIntimeIsNull() {
            addCriterion("Last_InTime is null");
            return (Criteria) this;
        }

        public Criteria andLastIntimeIsNotNull() {
            addCriterion("Last_InTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastIntimeEqualTo(Date value) {
            addCriterion("Last_InTime =", value, "lastIntime");
            return (Criteria) this;
        }

        public Criteria andLastIntimeNotEqualTo(Date value) {
            addCriterion("Last_InTime <>", value, "lastIntime");
            return (Criteria) this;
        }

        public Criteria andLastIntimeGreaterThan(Date value) {
            addCriterion("Last_InTime >", value, "lastIntime");
            return (Criteria) this;
        }

        public Criteria andLastIntimeGreaterThanOrEqualTo(Date value) {
            addCriterion("Last_InTime >=", value, "lastIntime");
            return (Criteria) this;
        }

        public Criteria andLastIntimeLessThan(Date value) {
            addCriterion("Last_InTime <", value, "lastIntime");
            return (Criteria) this;
        }

        public Criteria andLastIntimeLessThanOrEqualTo(Date value) {
            addCriterion("Last_InTime <=", value, "lastIntime");
            return (Criteria) this;
        }

        public Criteria andLastIntimeIn(List<Date> values) {
            addCriterion("Last_InTime in", values, "lastIntime");
            return (Criteria) this;
        }

        public Criteria andLastIntimeNotIn(List<Date> values) {
            addCriterion("Last_InTime not in", values, "lastIntime");
            return (Criteria) this;
        }

        public Criteria andLastIntimeBetween(Date value1, Date value2) {
            addCriterion("Last_InTime between", value1, value2, "lastIntime");
            return (Criteria) this;
        }

        public Criteria andLastIntimeNotBetween(Date value1, Date value2) {
            addCriterion("Last_InTime not between", value1, value2, "lastIntime");
            return (Criteria) this;
        }

        public Criteria andCasecityIsNull() {
            addCriterion("CaseCity is null");
            return (Criteria) this;
        }

        public Criteria andCasecityIsNotNull() {
            addCriterion("CaseCity is not null");
            return (Criteria) this;
        }

        public Criteria andCasecityEqualTo(String value) {
            addCriterion("CaseCity =", value, "casecity");
            return (Criteria) this;
        }

        public Criteria andCasecityNotEqualTo(String value) {
            addCriterion("CaseCity <>", value, "casecity");
            return (Criteria) this;
        }

        public Criteria andCasecityGreaterThan(String value) {
            addCriterion("CaseCity >", value, "casecity");
            return (Criteria) this;
        }

        public Criteria andCasecityGreaterThanOrEqualTo(String value) {
            addCriterion("CaseCity >=", value, "casecity");
            return (Criteria) this;
        }

        public Criteria andCasecityLessThan(String value) {
            addCriterion("CaseCity <", value, "casecity");
            return (Criteria) this;
        }

        public Criteria andCasecityLessThanOrEqualTo(String value) {
            addCriterion("CaseCity <=", value, "casecity");
            return (Criteria) this;
        }

        public Criteria andCasecityLike(String value) {
            addCriterion("CaseCity like", value, "casecity");
            return (Criteria) this;
        }

        public Criteria andCasecityNotLike(String value) {
            addCriterion("CaseCity not like", value, "casecity");
            return (Criteria) this;
        }

        public Criteria andCasecityIn(List<String> values) {
            addCriterion("CaseCity in", values, "casecity");
            return (Criteria) this;
        }

        public Criteria andCasecityNotIn(List<String> values) {
            addCriterion("CaseCity not in", values, "casecity");
            return (Criteria) this;
        }

        public Criteria andCasecityBetween(String value1, String value2) {
            addCriterion("CaseCity between", value1, value2, "casecity");
            return (Criteria) this;
        }

        public Criteria andCasecityNotBetween(String value1, String value2) {
            addCriterion("CaseCity not between", value1, value2, "casecity");
            return (Criteria) this;
        }

        public Criteria andProcesscityIsNull() {
            addCriterion("ProcessCity is null");
            return (Criteria) this;
        }

        public Criteria andProcesscityIsNotNull() {
            addCriterion("ProcessCity is not null");
            return (Criteria) this;
        }

        public Criteria andProcesscityEqualTo(String value) {
            addCriterion("ProcessCity =", value, "processcity");
            return (Criteria) this;
        }

        public Criteria andProcesscityNotEqualTo(String value) {
            addCriterion("ProcessCity <>", value, "processcity");
            return (Criteria) this;
        }

        public Criteria andProcesscityGreaterThan(String value) {
            addCriterion("ProcessCity >", value, "processcity");
            return (Criteria) this;
        }

        public Criteria andProcesscityGreaterThanOrEqualTo(String value) {
            addCriterion("ProcessCity >=", value, "processcity");
            return (Criteria) this;
        }

        public Criteria andProcesscityLessThan(String value) {
            addCriterion("ProcessCity <", value, "processcity");
            return (Criteria) this;
        }

        public Criteria andProcesscityLessThanOrEqualTo(String value) {
            addCriterion("ProcessCity <=", value, "processcity");
            return (Criteria) this;
        }

        public Criteria andProcesscityLike(String value) {
            addCriterion("ProcessCity like", value, "processcity");
            return (Criteria) this;
        }

        public Criteria andProcesscityNotLike(String value) {
            addCriterion("ProcessCity not like", value, "processcity");
            return (Criteria) this;
        }

        public Criteria andProcesscityIn(List<String> values) {
            addCriterion("ProcessCity in", values, "processcity");
            return (Criteria) this;
        }

        public Criteria andProcesscityNotIn(List<String> values) {
            addCriterion("ProcessCity not in", values, "processcity");
            return (Criteria) this;
        }

        public Criteria andProcesscityBetween(String value1, String value2) {
            addCriterion("ProcessCity between", value1, value2, "processcity");
            return (Criteria) this;
        }

        public Criteria andProcesscityNotBetween(String value1, String value2) {
            addCriterion("ProcessCity not between", value1, value2, "processcity");
            return (Criteria) this;
        }

        public Criteria andOwncityIsNull() {
            addCriterion("OwnCity is null");
            return (Criteria) this;
        }

        public Criteria andOwncityIsNotNull() {
            addCriterion("OwnCity is not null");
            return (Criteria) this;
        }

        public Criteria andOwncityEqualTo(String value) {
            addCriterion("OwnCity =", value, "owncity");
            return (Criteria) this;
        }

        public Criteria andOwncityNotEqualTo(String value) {
            addCriterion("OwnCity <>", value, "owncity");
            return (Criteria) this;
        }

        public Criteria andOwncityGreaterThan(String value) {
            addCriterion("OwnCity >", value, "owncity");
            return (Criteria) this;
        }

        public Criteria andOwncityGreaterThanOrEqualTo(String value) {
            addCriterion("OwnCity >=", value, "owncity");
            return (Criteria) this;
        }

        public Criteria andOwncityLessThan(String value) {
            addCriterion("OwnCity <", value, "owncity");
            return (Criteria) this;
        }

        public Criteria andOwncityLessThanOrEqualTo(String value) {
            addCriterion("OwnCity <=", value, "owncity");
            return (Criteria) this;
        }

        public Criteria andOwncityLike(String value) {
            addCriterion("OwnCity like", value, "owncity");
            return (Criteria) this;
        }

        public Criteria andOwncityNotLike(String value) {
            addCriterion("OwnCity not like", value, "owncity");
            return (Criteria) this;
        }

        public Criteria andOwncityIn(List<String> values) {
            addCriterion("OwnCity in", values, "owncity");
            return (Criteria) this;
        }

        public Criteria andOwncityNotIn(List<String> values) {
            addCriterion("OwnCity not in", values, "owncity");
            return (Criteria) this;
        }

        public Criteria andOwncityBetween(String value1, String value2) {
            addCriterion("OwnCity between", value1, value2, "owncity");
            return (Criteria) this;
        }

        public Criteria andOwncityNotBetween(String value1, String value2) {
            addCriterion("OwnCity not between", value1, value2, "owncity");
            return (Criteria) this;
        }

        public Criteria andBranchIsNull() {
            addCriterion("Branch is null");
            return (Criteria) this;
        }

        public Criteria andBranchIsNotNull() {
            addCriterion("Branch is not null");
            return (Criteria) this;
        }

        public Criteria andBranchEqualTo(String value) {
            addCriterion("Branch =", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchNotEqualTo(String value) {
            addCriterion("Branch <>", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchGreaterThan(String value) {
            addCriterion("Branch >", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchGreaterThanOrEqualTo(String value) {
            addCriterion("Branch >=", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchLessThan(String value) {
            addCriterion("Branch <", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchLessThanOrEqualTo(String value) {
            addCriterion("Branch <=", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchLike(String value) {
            addCriterion("Branch like", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchNotLike(String value) {
            addCriterion("Branch not like", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchIn(List<String> values) {
            addCriterion("Branch in", values, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchNotIn(List<String> values) {
            addCriterion("Branch not in", values, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchBetween(String value1, String value2) {
            addCriterion("Branch between", value1, value2, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchNotBetween(String value1, String value2) {
            addCriterion("Branch not between", value1, value2, "branch");
            return (Criteria) this;
        }

        public Criteria andOutsouringnoIsNull() {
            addCriterion("OutSouringNo is null");
            return (Criteria) this;
        }

        public Criteria andOutsouringnoIsNotNull() {
            addCriterion("OutSouringNo is not null");
            return (Criteria) this;
        }

        public Criteria andOutsouringnoEqualTo(String value) {
            addCriterion("OutSouringNo =", value, "outsouringno");
            return (Criteria) this;
        }

        public Criteria andOutsouringnoNotEqualTo(String value) {
            addCriterion("OutSouringNo <>", value, "outsouringno");
            return (Criteria) this;
        }

        public Criteria andOutsouringnoGreaterThan(String value) {
            addCriterion("OutSouringNo >", value, "outsouringno");
            return (Criteria) this;
        }

        public Criteria andOutsouringnoGreaterThanOrEqualTo(String value) {
            addCriterion("OutSouringNo >=", value, "outsouringno");
            return (Criteria) this;
        }

        public Criteria andOutsouringnoLessThan(String value) {
            addCriterion("OutSouringNo <", value, "outsouringno");
            return (Criteria) this;
        }

        public Criteria andOutsouringnoLessThanOrEqualTo(String value) {
            addCriterion("OutSouringNo <=", value, "outsouringno");
            return (Criteria) this;
        }

        public Criteria andOutsouringnoLike(String value) {
            addCriterion("OutSouringNo like", value, "outsouringno");
            return (Criteria) this;
        }

        public Criteria andOutsouringnoNotLike(String value) {
            addCriterion("OutSouringNo not like", value, "outsouringno");
            return (Criteria) this;
        }

        public Criteria andOutsouringnoIn(List<String> values) {
            addCriterion("OutSouringNo in", values, "outsouringno");
            return (Criteria) this;
        }

        public Criteria andOutsouringnoNotIn(List<String> values) {
            addCriterion("OutSouringNo not in", values, "outsouringno");
            return (Criteria) this;
        }

        public Criteria andOutsouringnoBetween(String value1, String value2) {
            addCriterion("OutSouringNo between", value1, value2, "outsouringno");
            return (Criteria) this;
        }

        public Criteria andOutsouringnoNotBetween(String value1, String value2) {
            addCriterion("OutSouringNo not between", value1, value2, "outsouringno");
            return (Criteria) this;
        }

        public Criteria andOricaseNoIsNull() {
            addCriterion("oriCase_No is null");
            return (Criteria) this;
        }

        public Criteria andOricaseNoIsNotNull() {
            addCriterion("oriCase_No is not null");
            return (Criteria) this;
        }

        public Criteria andOricaseNoEqualTo(String value) {
            addCriterion("oriCase_No =", value, "oricaseNo");
            return (Criteria) this;
        }

        public Criteria andOricaseNoNotEqualTo(String value) {
            addCriterion("oriCase_No <>", value, "oricaseNo");
            return (Criteria) this;
        }

        public Criteria andOricaseNoGreaterThan(String value) {
            addCriterion("oriCase_No >", value, "oricaseNo");
            return (Criteria) this;
        }

        public Criteria andOricaseNoGreaterThanOrEqualTo(String value) {
            addCriterion("oriCase_No >=", value, "oricaseNo");
            return (Criteria) this;
        }

        public Criteria andOricaseNoLessThan(String value) {
            addCriterion("oriCase_No <", value, "oricaseNo");
            return (Criteria) this;
        }

        public Criteria andOricaseNoLessThanOrEqualTo(String value) {
            addCriterion("oriCase_No <=", value, "oricaseNo");
            return (Criteria) this;
        }

        public Criteria andOricaseNoLike(String value) {
            addCriterion("oriCase_No like", value, "oricaseNo");
            return (Criteria) this;
        }

        public Criteria andOricaseNoNotLike(String value) {
            addCriterion("oriCase_No not like", value, "oricaseNo");
            return (Criteria) this;
        }

        public Criteria andOricaseNoIn(List<String> values) {
            addCriterion("oriCase_No in", values, "oricaseNo");
            return (Criteria) this;
        }

        public Criteria andOricaseNoNotIn(List<String> values) {
            addCriterion("oriCase_No not in", values, "oricaseNo");
            return (Criteria) this;
        }

        public Criteria andOricaseNoBetween(String value1, String value2) {
            addCriterion("oriCase_No between", value1, value2, "oricaseNo");
            return (Criteria) this;
        }

        public Criteria andOricaseNoNotBetween(String value1, String value2) {
            addCriterion("oriCase_No not between", value1, value2, "oricaseNo");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeIsNull() {
            addCriterion("Currency_Type is null");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeIsNotNull() {
            addCriterion("Currency_Type is not null");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeEqualTo(String value) {
            addCriterion("Currency_Type =", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeNotEqualTo(String value) {
            addCriterion("Currency_Type <>", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeGreaterThan(String value) {
            addCriterion("Currency_Type >", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeGreaterThanOrEqualTo(String value) {
            addCriterion("Currency_Type >=", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeLessThan(String value) {
            addCriterion("Currency_Type <", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeLessThanOrEqualTo(String value) {
            addCriterion("Currency_Type <=", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeLike(String value) {
            addCriterion("Currency_Type like", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeNotLike(String value) {
            addCriterion("Currency_Type not like", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeIn(List<String> values) {
            addCriterion("Currency_Type in", values, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeNotIn(List<String> values) {
            addCriterion("Currency_Type not in", values, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeBetween(String value1, String value2) {
            addCriterion("Currency_Type between", value1, value2, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeNotBetween(String value1, String value2) {
            addCriterion("Currency_Type not between", value1, value2, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCategorize2IsNull() {
            addCriterion("Categorize2 is null");
            return (Criteria) this;
        }

        public Criteria andCategorize2IsNotNull() {
            addCriterion("Categorize2 is not null");
            return (Criteria) this;
        }

        public Criteria andCategorize2EqualTo(String value) {
            addCriterion("Categorize2 =", value, "categorize2");
            return (Criteria) this;
        }

        public Criteria andCategorize2NotEqualTo(String value) {
            addCriterion("Categorize2 <>", value, "categorize2");
            return (Criteria) this;
        }

        public Criteria andCategorize2GreaterThan(String value) {
            addCriterion("Categorize2 >", value, "categorize2");
            return (Criteria) this;
        }

        public Criteria andCategorize2GreaterThanOrEqualTo(String value) {
            addCriterion("Categorize2 >=", value, "categorize2");
            return (Criteria) this;
        }

        public Criteria andCategorize2LessThan(String value) {
            addCriterion("Categorize2 <", value, "categorize2");
            return (Criteria) this;
        }

        public Criteria andCategorize2LessThanOrEqualTo(String value) {
            addCriterion("Categorize2 <=", value, "categorize2");
            return (Criteria) this;
        }

        public Criteria andCategorize2Like(String value) {
            addCriterion("Categorize2 like", value, "categorize2");
            return (Criteria) this;
        }

        public Criteria andCategorize2NotLike(String value) {
            addCriterion("Categorize2 not like", value, "categorize2");
            return (Criteria) this;
        }

        public Criteria andCategorize2In(List<String> values) {
            addCriterion("Categorize2 in", values, "categorize2");
            return (Criteria) this;
        }

        public Criteria andCategorize2NotIn(List<String> values) {
            addCriterion("Categorize2 not in", values, "categorize2");
            return (Criteria) this;
        }

        public Criteria andCategorize2Between(String value1, String value2) {
            addCriterion("Categorize2 between", value1, value2, "categorize2");
            return (Criteria) this;
        }

        public Criteria andCategorize2NotBetween(String value1, String value2) {
            addCriterion("Categorize2 not between", value1, value2, "categorize2");
            return (Criteria) this;
        }

        public Criteria andCaseamountIsNull() {
            addCriterion("CaseAmount is null");
            return (Criteria) this;
        }

        public Criteria andCaseamountIsNotNull() {
            addCriterion("CaseAmount is not null");
            return (Criteria) this;
        }

        public Criteria andCaseamountEqualTo(BigDecimal value) {
            addCriterion("CaseAmount =", value, "caseamount");
            return (Criteria) this;
        }

        public Criteria andCaseamountNotEqualTo(BigDecimal value) {
            addCriterion("CaseAmount <>", value, "caseamount");
            return (Criteria) this;
        }

        public Criteria andCaseamountGreaterThan(BigDecimal value) {
            addCriterion("CaseAmount >", value, "caseamount");
            return (Criteria) this;
        }

        public Criteria andCaseamountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CaseAmount >=", value, "caseamount");
            return (Criteria) this;
        }

        public Criteria andCaseamountLessThan(BigDecimal value) {
            addCriterion("CaseAmount <", value, "caseamount");
            return (Criteria) this;
        }

        public Criteria andCaseamountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CaseAmount <=", value, "caseamount");
            return (Criteria) this;
        }

        public Criteria andCaseamountIn(List<BigDecimal> values) {
            addCriterion("CaseAmount in", values, "caseamount");
            return (Criteria) this;
        }

        public Criteria andCaseamountNotIn(List<BigDecimal> values) {
            addCriterion("CaseAmount not in", values, "caseamount");
            return (Criteria) this;
        }

        public Criteria andCaseamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CaseAmount between", value1, value2, "caseamount");
            return (Criteria) this;
        }

        public Criteria andCaseamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CaseAmount not between", value1, value2, "caseamount");
            return (Criteria) this;
        }

        public Criteria andCaseowemoneyIsNull() {
            addCriterion("CaseOweMoney is null");
            return (Criteria) this;
        }

        public Criteria andCaseowemoneyIsNotNull() {
            addCriterion("CaseOweMoney is not null");
            return (Criteria) this;
        }

        public Criteria andCaseowemoneyEqualTo(BigDecimal value) {
            addCriterion("CaseOweMoney =", value, "caseowemoney");
            return (Criteria) this;
        }

        public Criteria andCaseowemoneyNotEqualTo(BigDecimal value) {
            addCriterion("CaseOweMoney <>", value, "caseowemoney");
            return (Criteria) this;
        }

        public Criteria andCaseowemoneyGreaterThan(BigDecimal value) {
            addCriterion("CaseOweMoney >", value, "caseowemoney");
            return (Criteria) this;
        }

        public Criteria andCaseowemoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CaseOweMoney >=", value, "caseowemoney");
            return (Criteria) this;
        }

        public Criteria andCaseowemoneyLessThan(BigDecimal value) {
            addCriterion("CaseOweMoney <", value, "caseowemoney");
            return (Criteria) this;
        }

        public Criteria andCaseowemoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CaseOweMoney <=", value, "caseowemoney");
            return (Criteria) this;
        }

        public Criteria andCaseowemoneyIn(List<BigDecimal> values) {
            addCriterion("CaseOweMoney in", values, "caseowemoney");
            return (Criteria) this;
        }

        public Criteria andCaseowemoneyNotIn(List<BigDecimal> values) {
            addCriterion("CaseOweMoney not in", values, "caseowemoney");
            return (Criteria) this;
        }

        public Criteria andCaseowemoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CaseOweMoney between", value1, value2, "caseowemoney");
            return (Criteria) this;
        }

        public Criteria andCaseowemoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CaseOweMoney not between", value1, value2, "caseowemoney");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("Sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("Sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("Sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("Sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("Sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("Sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("Sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("Sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("Sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("Sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("Sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("Sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("Sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("Sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andPrecaseTypeIsNull() {
            addCriterion("PreCase_Type is null");
            return (Criteria) this;
        }

        public Criteria andPrecaseTypeIsNotNull() {
            addCriterion("PreCase_Type is not null");
            return (Criteria) this;
        }

        public Criteria andPrecaseTypeEqualTo(String value) {
            addCriterion("PreCase_Type =", value, "precaseType");
            return (Criteria) this;
        }

        public Criteria andPrecaseTypeNotEqualTo(String value) {
            addCriterion("PreCase_Type <>", value, "precaseType");
            return (Criteria) this;
        }

        public Criteria andPrecaseTypeGreaterThan(String value) {
            addCriterion("PreCase_Type >", value, "precaseType");
            return (Criteria) this;
        }

        public Criteria andPrecaseTypeGreaterThanOrEqualTo(String value) {
            addCriterion("PreCase_Type >=", value, "precaseType");
            return (Criteria) this;
        }

        public Criteria andPrecaseTypeLessThan(String value) {
            addCriterion("PreCase_Type <", value, "precaseType");
            return (Criteria) this;
        }

        public Criteria andPrecaseTypeLessThanOrEqualTo(String value) {
            addCriterion("PreCase_Type <=", value, "precaseType");
            return (Criteria) this;
        }

        public Criteria andPrecaseTypeLike(String value) {
            addCriterion("PreCase_Type like", value, "precaseType");
            return (Criteria) this;
        }

        public Criteria andPrecaseTypeNotLike(String value) {
            addCriterion("PreCase_Type not like", value, "precaseType");
            return (Criteria) this;
        }

        public Criteria andPrecaseTypeIn(List<String> values) {
            addCriterion("PreCase_Type in", values, "precaseType");
            return (Criteria) this;
        }

        public Criteria andPrecaseTypeNotIn(List<String> values) {
            addCriterion("PreCase_Type not in", values, "precaseType");
            return (Criteria) this;
        }

        public Criteria andPrecaseTypeBetween(String value1, String value2) {
            addCriterion("PreCase_Type between", value1, value2, "precaseType");
            return (Criteria) this;
        }

        public Criteria andPrecaseTypeNotBetween(String value1, String value2) {
            addCriterion("PreCase_Type not between", value1, value2, "precaseType");
            return (Criteria) this;
        }

        public Criteria andPrecateNoIsNull() {
            addCriterion("PreCate_No is null");
            return (Criteria) this;
        }

        public Criteria andPrecateNoIsNotNull() {
            addCriterion("PreCate_No is not null");
            return (Criteria) this;
        }

        public Criteria andPrecateNoEqualTo(String value) {
            addCriterion("PreCate_No =", value, "precateNo");
            return (Criteria) this;
        }

        public Criteria andPrecateNoNotEqualTo(String value) {
            addCriterion("PreCate_No <>", value, "precateNo");
            return (Criteria) this;
        }

        public Criteria andPrecateNoGreaterThan(String value) {
            addCriterion("PreCate_No >", value, "precateNo");
            return (Criteria) this;
        }

        public Criteria andPrecateNoGreaterThanOrEqualTo(String value) {
            addCriterion("PreCate_No >=", value, "precateNo");
            return (Criteria) this;
        }

        public Criteria andPrecateNoLessThan(String value) {
            addCriterion("PreCate_No <", value, "precateNo");
            return (Criteria) this;
        }

        public Criteria andPrecateNoLessThanOrEqualTo(String value) {
            addCriterion("PreCate_No <=", value, "precateNo");
            return (Criteria) this;
        }

        public Criteria andPrecateNoLike(String value) {
            addCriterion("PreCate_No like", value, "precateNo");
            return (Criteria) this;
        }

        public Criteria andPrecateNoNotLike(String value) {
            addCriterion("PreCate_No not like", value, "precateNo");
            return (Criteria) this;
        }

        public Criteria andPrecateNoIn(List<String> values) {
            addCriterion("PreCate_No in", values, "precateNo");
            return (Criteria) this;
        }

        public Criteria andPrecateNoNotIn(List<String> values) {
            addCriterion("PreCate_No not in", values, "precateNo");
            return (Criteria) this;
        }

        public Criteria andPrecateNoBetween(String value1, String value2) {
            addCriterion("PreCate_No between", value1, value2, "precateNo");
            return (Criteria) this;
        }

        public Criteria andPrecateNoNotBetween(String value1, String value2) {
            addCriterion("PreCate_No not between", value1, value2, "precateNo");
            return (Criteria) this;
        }

        public Criteria andReturntextIsNull() {
            addCriterion("ReturnText is null");
            return (Criteria) this;
        }

        public Criteria andReturntextIsNotNull() {
            addCriterion("ReturnText is not null");
            return (Criteria) this;
        }

        public Criteria andReturntextEqualTo(String value) {
            addCriterion("ReturnText =", value, "returntext");
            return (Criteria) this;
        }

        public Criteria andReturntextNotEqualTo(String value) {
            addCriterion("ReturnText <>", value, "returntext");
            return (Criteria) this;
        }

        public Criteria andReturntextGreaterThan(String value) {
            addCriterion("ReturnText >", value, "returntext");
            return (Criteria) this;
        }

        public Criteria andReturntextGreaterThanOrEqualTo(String value) {
            addCriterion("ReturnText >=", value, "returntext");
            return (Criteria) this;
        }

        public Criteria andReturntextLessThan(String value) {
            addCriterion("ReturnText <", value, "returntext");
            return (Criteria) this;
        }

        public Criteria andReturntextLessThanOrEqualTo(String value) {
            addCriterion("ReturnText <=", value, "returntext");
            return (Criteria) this;
        }

        public Criteria andReturntextLike(String value) {
            addCriterion("ReturnText like", value, "returntext");
            return (Criteria) this;
        }

        public Criteria andReturntextNotLike(String value) {
            addCriterion("ReturnText not like", value, "returntext");
            return (Criteria) this;
        }

        public Criteria andReturntextIn(List<String> values) {
            addCriterion("ReturnText in", values, "returntext");
            return (Criteria) this;
        }

        public Criteria andReturntextNotIn(List<String> values) {
            addCriterion("ReturnText not in", values, "returntext");
            return (Criteria) this;
        }

        public Criteria andReturntextBetween(String value1, String value2) {
            addCriterion("ReturnText between", value1, value2, "returntext");
            return (Criteria) this;
        }

        public Criteria andReturntextNotBetween(String value1, String value2) {
            addCriterion("ReturnText not between", value1, value2, "returntext");
            return (Criteria) this;
        }

        public Criteria andRowguidIsNull() {
            addCriterion("rowguid is null");
            return (Criteria) this;
        }

        public Criteria andRowguidIsNotNull() {
            addCriterion("rowguid is not null");
            return (Criteria) this;
        }

        public Criteria andRowguidEqualTo(String value) {
            addCriterion("rowguid =", value, "rowguid");
            return (Criteria) this;
        }

        public Criteria andRowguidNotEqualTo(String value) {
            addCriterion("rowguid <>", value, "rowguid");
            return (Criteria) this;
        }

        public Criteria andRowguidGreaterThan(String value) {
            addCriterion("rowguid >", value, "rowguid");
            return (Criteria) this;
        }

        public Criteria andRowguidGreaterThanOrEqualTo(String value) {
            addCriterion("rowguid >=", value, "rowguid");
            return (Criteria) this;
        }

        public Criteria andRowguidLessThan(String value) {
            addCriterion("rowguid <", value, "rowguid");
            return (Criteria) this;
        }

        public Criteria andRowguidLessThanOrEqualTo(String value) {
            addCriterion("rowguid <=", value, "rowguid");
            return (Criteria) this;
        }

        public Criteria andRowguidLike(String value) {
            addCriterion("rowguid like", value, "rowguid");
            return (Criteria) this;
        }

        public Criteria andRowguidNotLike(String value) {
            addCriterion("rowguid not like", value, "rowguid");
            return (Criteria) this;
        }

        public Criteria andRowguidIn(List<String> values) {
            addCriterion("rowguid in", values, "rowguid");
            return (Criteria) this;
        }

        public Criteria andRowguidNotIn(List<String> values) {
            addCriterion("rowguid not in", values, "rowguid");
            return (Criteria) this;
        }

        public Criteria andRowguidBetween(String value1, String value2) {
            addCriterion("rowguid between", value1, value2, "rowguid");
            return (Criteria) this;
        }

        public Criteria andRowguidNotBetween(String value1, String value2) {
            addCriterion("rowguid not between", value1, value2, "rowguid");
            return (Criteria) this;
        }

        public Criteria andCaseNoLikeInsensitive(String value) {
            addCriterion("upper(Case_No) like", value.toUpperCase(), "caseNo");
            return (Criteria) this;
        }

        public Criteria andCoNoLikeInsensitive(String value) {
            addCriterion("upper(Co_No) like", value.toUpperCase(), "coNo");
            return (Criteria) this;
        }

        public Criteria andItemnoLikeInsensitive(String value) {
            addCriterion("upper(ItemNo) like", value.toUpperCase(), "itemno");
            return (Criteria) this;
        }

        public Criteria andBatnumLikeInsensitive(String value) {
            addCriterion("upper(BatNum) like", value.toUpperCase(), "batnum");
            return (Criteria) this;
        }

        public Criteria andCaseTypeLikeInsensitive(String value) {
            addCriterion("upper(Case_Type) like", value.toUpperCase(), "caseType");
            return (Criteria) this;
        }

        public Criteria andCateNoLikeInsensitive(String value) {
            addCriterion("upper(Cate_No) like", value.toUpperCase(), "cateNo");
            return (Criteria) this;
        }

        public Criteria andPnameLikeInsensitive(String value) {
            addCriterion("upper(PName) like", value.toUpperCase(), "pname");
            return (Criteria) this;
        }

        public Criteria andPidLikeInsensitive(String value) {
            addCriterion("upper(PID) like", value.toUpperCase(), "pid");
            return (Criteria) this;
        }

        public Criteria andRemLikeInsensitive(String value) {
            addCriterion("upper(Rem) like", value.toUpperCase(), "rem");
            return (Criteria) this;
        }

        public Criteria andIncomenoLikeInsensitive(String value) {
            addCriterion("upper(IncomeNo) like", value.toUpperCase(), "incomeno");
            return (Criteria) this;
        }

        public Criteria andRetremLikeInsensitive(String value) {
            addCriterion("upper(RetRem) like", value.toUpperCase(), "retrem");
            return (Criteria) this;
        }

        public Criteria andRem1LikeInsensitive(String value) {
            addCriterion("upper(Rem1) like", value.toUpperCase(), "rem1");
            return (Criteria) this;
        }

        public Criteria andNotesLikeInsensitive(String value) {
            addCriterion("upper(Notes) like", value.toUpperCase(), "notes");
            return (Criteria) this;
        }

        public Criteria andMflagLikeInsensitive(String value) {
            addCriterion("upper(MFlag) like", value.toUpperCase(), "mflag");
            return (Criteria) this;
        }

        public Criteria andCasecityLikeInsensitive(String value) {
            addCriterion("upper(CaseCity) like", value.toUpperCase(), "casecity");
            return (Criteria) this;
        }

        public Criteria andProcesscityLikeInsensitive(String value) {
            addCriterion("upper(ProcessCity) like", value.toUpperCase(), "processcity");
            return (Criteria) this;
        }

        public Criteria andOwncityLikeInsensitive(String value) {
            addCriterion("upper(OwnCity) like", value.toUpperCase(), "owncity");
            return (Criteria) this;
        }

        public Criteria andBranchLikeInsensitive(String value) {
            addCriterion("upper(Branch) like", value.toUpperCase(), "branch");
            return (Criteria) this;
        }

        public Criteria andOutsouringnoLikeInsensitive(String value) {
            addCriterion("upper(OutSouringNo) like", value.toUpperCase(), "outsouringno");
            return (Criteria) this;
        }

        public Criteria andOricaseNoLikeInsensitive(String value) {
            addCriterion("upper(oriCase_No) like", value.toUpperCase(), "oricaseNo");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeLikeInsensitive(String value) {
            addCriterion("upper(Currency_Type) like", value.toUpperCase(), "currencyType");
            return (Criteria) this;
        }

        public Criteria andCategorize2LikeInsensitive(String value) {
            addCriterion("upper(Categorize2) like", value.toUpperCase(), "categorize2");
            return (Criteria) this;
        }

        public Criteria andSexLikeInsensitive(String value) {
            addCriterion("upper(Sex) like", value.toUpperCase(), "sex");
            return (Criteria) this;
        }

        public Criteria andPrecaseTypeLikeInsensitive(String value) {
            addCriterion("upper(PreCase_Type) like", value.toUpperCase(), "precaseType");
            return (Criteria) this;
        }

        public Criteria andPrecateNoLikeInsensitive(String value) {
            addCriterion("upper(PreCate_No) like", value.toUpperCase(), "precateNo");
            return (Criteria) this;
        }

        public Criteria andReturntextLikeInsensitive(String value) {
            addCriterion("upper(ReturnText) like", value.toUpperCase(), "returntext");
            return (Criteria) this;
        }

        public Criteria andRowguidLikeInsensitive(String value) {
            addCriterion("upper(rowguid) like", value.toUpperCase(), "rowguid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MTMCaseData
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MTMCaseData
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}