package mybatis.one.mapper;

import java.util.List;
import mybatis.one.po.DBAdminUserInfo;
import mybatis.one.po.DBAdminUserInfoExample;
import org.apache.ibatis.annotations.Param;

public interface DBAdminUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_userinfo
     *
     * @mbggenerated
     */
    int countByExample(DBAdminUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_userinfo
     *
     * @mbggenerated
     */
    int deleteByExample(DBAdminUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_userinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_userinfo
     *
     * @mbggenerated
     */
    int insert(DBAdminUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_userinfo
     *
     * @mbggenerated
     */
    int insertSelective(DBAdminUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_userinfo
     *
     * @mbggenerated
     */
    List<DBAdminUserInfo> selectByExample(DBAdminUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_userinfo
     *
     * @mbggenerated
     */
    DBAdminUserInfo selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_userinfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DBAdminUserInfo record, @Param("example") DBAdminUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_userinfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DBAdminUserInfo record, @Param("example") DBAdminUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_userinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DBAdminUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_userinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DBAdminUserInfo record);
}