package mybatis.one.mapper;

import java.util.List;
import mybatis.one.po.DBAdminRoleMenu;
import mybatis.one.po.DBAdminRoleMenuExample;
import org.apache.ibatis.annotations.Param;

public interface DBAdminRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_rolemenu
     *
     * @mbggenerated
     */
    int countByExample(DBAdminRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_rolemenu
     *
     * @mbggenerated
     */
    int deleteByExample(DBAdminRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_rolemenu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer rolemenuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_rolemenu
     *
     * @mbggenerated
     */
    int insert(DBAdminRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_rolemenu
     *
     * @mbggenerated
     */
    int insertSelective(DBAdminRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_rolemenu
     *
     * @mbggenerated
     */
    List<DBAdminRoleMenu> selectByExample(DBAdminRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_rolemenu
     *
     * @mbggenerated
     */
    DBAdminRoleMenu selectByPrimaryKey(Integer rolemenuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_rolemenu
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DBAdminRoleMenu record, @Param("example") DBAdminRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_rolemenu
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DBAdminRoleMenu record, @Param("example") DBAdminRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_rolemenu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DBAdminRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_rolemenu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DBAdminRoleMenu record);
}