package mybatis.one.mapper;

import java.util.List;
import mybatis.one.po.DBAdminRole;
import mybatis.one.po.DBAdminRoleExample;
import org.apache.ibatis.annotations.Param;

public interface DBAdminRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated
     */
    int countByExample(DBAdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated
     */
    int deleteByExample(DBAdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated
     */
    int insert(DBAdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated
     */
    int insertSelective(DBAdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated
     */
    List<DBAdminRole> selectByExample(DBAdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated
     */
    DBAdminRole selectByPrimaryKey(Integer roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DBAdminRole record, @Param("example") DBAdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DBAdminRole record, @Param("example") DBAdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DBAdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DBAdminRole record);
}