package mybatis.one.mapper;

import java.util.List;
import mybatis.one.po.DBAdminUserRole;
import mybatis.one.po.DBAdminUserRoleExample;
import org.apache.ibatis.annotations.Param;

public interface DBAdminUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_userrole
     *
     * @mbggenerated
     */
    int countByExample(DBAdminUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_userrole
     *
     * @mbggenerated
     */
    int deleteByExample(DBAdminUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_userrole
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userroleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_userrole
     *
     * @mbggenerated
     */
    int insert(DBAdminUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_userrole
     *
     * @mbggenerated
     */
    int insertSelective(DBAdminUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_userrole
     *
     * @mbggenerated
     */
    List<DBAdminUserRole> selectByExample(DBAdminUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_userrole
     *
     * @mbggenerated
     */
    DBAdminUserRole selectByPrimaryKey(Integer userroleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_userrole
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DBAdminUserRole record, @Param("example") DBAdminUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_userrole
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DBAdminUserRole record, @Param("example") DBAdminUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_userrole
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DBAdminUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_userrole
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DBAdminUserRole record);
}