package mybatis.one.mapper;

import java.util.List;
import mybatis.one.po.DBAdminMenu;
import mybatis.one.po.DBAdminMenuExample;
import org.apache.ibatis.annotations.Param;

public interface DBAdminMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbggenerated
     */
    int countByExample(DBAdminMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbggenerated
     */
    int deleteByExample(DBAdminMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer menuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbggenerated
     */
    int insert(DBAdminMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbggenerated
     */
    int insertSelective(DBAdminMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbggenerated
     */
    List<DBAdminMenu> selectByExample(DBAdminMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbggenerated
     */
    DBAdminMenu selectByPrimaryKey(Integer menuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DBAdminMenu record, @Param("example") DBAdminMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DBAdminMenu record, @Param("example") DBAdminMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DBAdminMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DBAdminMenu record);
}