package mybatis.one.mapper;

import java.util.List;
import mybatis.one.po.DBImgZB;
import mybatis.one.po.DBImgZBExample;
import org.apache.ibatis.annotations.Param;

public interface DBImgZBMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgzb
     *
     * @mbggenerated
     */
    int countByExample(DBImgZBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgzb
     *
     * @mbggenerated
     */
    int deleteByExample(DBImgZBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgzb
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String imagename);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgzb
     *
     * @mbggenerated
     */
    int insert(DBImgZB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgzb
     *
     * @mbggenerated
     */
    int insertSelective(DBImgZB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgzb
     *
     * @mbggenerated
     */
    List<DBImgZB> selectByExample(DBImgZBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgzb
     *
     * @mbggenerated
     */
    DBImgZB selectByPrimaryKey(String imagename);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgzb
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DBImgZB record, @Param("example") DBImgZBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgzb
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DBImgZB record, @Param("example") DBImgZBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgzb
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DBImgZB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgzb
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DBImgZB record);
}