package mybatis.one.mapper;

import java.util.List;
import mybatis.one.po.DBImportBatch;
import mybatis.one.po.DBImportBatchExample;
import org.apache.ibatis.annotations.Param;

public interface DBImportBatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importbatch
     *
     * @mbggenerated
     */
    int countByExample(DBImportBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importbatch
     *
     * @mbggenerated
     */
    int deleteByExample(DBImportBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importbatch
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long seqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importbatch
     *
     * @mbggenerated
     */
    int insert(DBImportBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importbatch
     *
     * @mbggenerated
     */
    int insertSelective(DBImportBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importbatch
     *
     * @mbggenerated
     */
    List<DBImportBatch> selectByExample(DBImportBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importbatch
     *
     * @mbggenerated
     */
    DBImportBatch selectByPrimaryKey(Long seqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importbatch
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DBImportBatch record, @Param("example") DBImportBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importbatch
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DBImportBatch record, @Param("example") DBImportBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importbatch
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DBImportBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importbatch
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DBImportBatch record);
}