package mybatis.one.mapper;

import java.util.List;
import mybatis.one.po.DBRecogs;
import mybatis.one.po.DBRecogsExample;
import org.apache.ibatis.annotations.Param;

public interface DBRecogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recogs
     *
     * @mbggenerated
     */
    int countByExample(DBRecogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recogs
     *
     * @mbggenerated
     */
    int deleteByExample(DBRecogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recogs
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long seqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recogs
     *
     * @mbggenerated
     */
    int insert(DBRecogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recogs
     *
     * @mbggenerated
     */
    int insertSelective(DBRecogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recogs
     *
     * @mbggenerated
     */
    List<DBRecogs> selectByExample(DBRecogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recogs
     *
     * @mbggenerated
     */
    DBRecogs selectByPrimaryKey(Long seqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recogs
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DBRecogs record, @Param("example") DBRecogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recogs
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DBRecogs record, @Param("example") DBRecogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recogs
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DBRecogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recogs
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DBRecogs record);
}