package mybatis.one.mapper;

import java.util.List;
import mybatis.one.po.DBZNUpdateInfo;
import mybatis.one.po.DBZNUpdateInfoExample;
import org.apache.ibatis.annotations.Param;

public interface DBZNUpdateInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table znupdateinfo
     *
     * @mbggenerated
     */
    int countByExample(DBZNUpdateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table znupdateinfo
     *
     * @mbggenerated
     */
    int deleteByExample(DBZNUpdateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table znupdateinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long seqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table znupdateinfo
     *
     * @mbggenerated
     */
    int insert(DBZNUpdateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table znupdateinfo
     *
     * @mbggenerated
     */
    int insertSelective(DBZNUpdateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table znupdateinfo
     *
     * @mbggenerated
     */
    List<DBZNUpdateInfo> selectByExample(DBZNUpdateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table znupdateinfo
     *
     * @mbggenerated
     */
    DBZNUpdateInfo selectByPrimaryKey(Long seqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table znupdateinfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DBZNUpdateInfo record, @Param("example") DBZNUpdateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table znupdateinfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DBZNUpdateInfo record, @Param("example") DBZNUpdateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table znupdateinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DBZNUpdateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table znupdateinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DBZNUpdateInfo record);
}