package mybatis.one.po;

import java.io.Serializable;
import java.util.Date;

public class DBAdminUserRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_userrole.userroleid
     *
     * @mbggenerated
     */
    private Integer userroleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_userrole.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_userrole.roleid
     *
     * @mbggenerated
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_userrole.createuserid
     *
     * @mbggenerated
     */
    private Integer createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_userrole.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_userrole.modifyuserid
     *
     * @mbggenerated
     */
    private Integer modifyuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_userrole.modifytime
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_userrole
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_userrole.userroleid
     *
     * @return the value of admin_userrole.userroleid
     *
     * @mbggenerated
     */
    public Integer getUserroleid() {
        return userroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_userrole.userroleid
     *
     * @param userroleid the value for admin_userrole.userroleid
     *
     * @mbggenerated
     */
    public void setUserroleid(Integer userroleid) {
        this.userroleid = userroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_userrole.userid
     *
     * @return the value of admin_userrole.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_userrole.userid
     *
     * @param userid the value for admin_userrole.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_userrole.roleid
     *
     * @return the value of admin_userrole.roleid
     *
     * @mbggenerated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_userrole.roleid
     *
     * @param roleid the value for admin_userrole.roleid
     *
     * @mbggenerated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_userrole.createuserid
     *
     * @return the value of admin_userrole.createuserid
     *
     * @mbggenerated
     */
    public Integer getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_userrole.createuserid
     *
     * @param createuserid the value for admin_userrole.createuserid
     *
     * @mbggenerated
     */
    public void setCreateuserid(Integer createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_userrole.createtime
     *
     * @return the value of admin_userrole.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_userrole.createtime
     *
     * @param createtime the value for admin_userrole.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_userrole.modifyuserid
     *
     * @return the value of admin_userrole.modifyuserid
     *
     * @mbggenerated
     */
    public Integer getModifyuserid() {
        return modifyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_userrole.modifyuserid
     *
     * @param modifyuserid the value for admin_userrole.modifyuserid
     *
     * @mbggenerated
     */
    public void setModifyuserid(Integer modifyuserid) {
        this.modifyuserid = modifyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_userrole.modifytime
     *
     * @return the value of admin_userrole.modifytime
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_userrole.modifytime
     *
     * @param modifytime the value for admin_userrole.modifytime
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }
}