package mybatis.one.po;

import java.io.Serializable;
import java.util.Date;

public class DBAdminRoleMenu implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_rolemenu.rolemenuid
     *
     * @mbggenerated
     */
    private Integer rolemenuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_rolemenu.roleid
     *
     * @mbggenerated
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_rolemenu.menuid
     *
     * @mbggenerated
     */
    private Integer menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_rolemenu.position
     *
     * @mbggenerated
     */
    private Integer position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_rolemenu.createuserid
     *
     * @mbggenerated
     */
    private Integer createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_rolemenu.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_rolemenu.modifyuserid
     *
     * @mbggenerated
     */
    private Integer modifyuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_rolemenu.modifytime
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_rolemenu
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_rolemenu.rolemenuid
     *
     * @return the value of admin_rolemenu.rolemenuid
     *
     * @mbggenerated
     */
    public Integer getRolemenuid() {
        return rolemenuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_rolemenu.rolemenuid
     *
     * @param rolemenuid the value for admin_rolemenu.rolemenuid
     *
     * @mbggenerated
     */
    public void setRolemenuid(Integer rolemenuid) {
        this.rolemenuid = rolemenuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_rolemenu.roleid
     *
     * @return the value of admin_rolemenu.roleid
     *
     * @mbggenerated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_rolemenu.roleid
     *
     * @param roleid the value for admin_rolemenu.roleid
     *
     * @mbggenerated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_rolemenu.menuid
     *
     * @return the value of admin_rolemenu.menuid
     *
     * @mbggenerated
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_rolemenu.menuid
     *
     * @param menuid the value for admin_rolemenu.menuid
     *
     * @mbggenerated
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_rolemenu.position
     *
     * @return the value of admin_rolemenu.position
     *
     * @mbggenerated
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_rolemenu.position
     *
     * @param position the value for admin_rolemenu.position
     *
     * @mbggenerated
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_rolemenu.createuserid
     *
     * @return the value of admin_rolemenu.createuserid
     *
     * @mbggenerated
     */
    public Integer getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_rolemenu.createuserid
     *
     * @param createuserid the value for admin_rolemenu.createuserid
     *
     * @mbggenerated
     */
    public void setCreateuserid(Integer createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_rolemenu.createtime
     *
     * @return the value of admin_rolemenu.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_rolemenu.createtime
     *
     * @param createtime the value for admin_rolemenu.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_rolemenu.modifyuserid
     *
     * @return the value of admin_rolemenu.modifyuserid
     *
     * @mbggenerated
     */
    public Integer getModifyuserid() {
        return modifyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_rolemenu.modifyuserid
     *
     * @param modifyuserid the value for admin_rolemenu.modifyuserid
     *
     * @mbggenerated
     */
    public void setModifyuserid(Integer modifyuserid) {
        this.modifyuserid = modifyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_rolemenu.modifytime
     *
     * @return the value of admin_rolemenu.modifytime
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_rolemenu.modifytime
     *
     * @param modifytime the value for admin_rolemenu.modifytime
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }
}