package mybatis.one.po;

import java.io.Serializable;
import java.util.Date;

public class DBImgZB implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgzb.imagename
     *
     * @mbggenerated
     */
    private String imagename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgzb.merchid
     *
     * @mbggenerated
     */
    private String merchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgzb.batchid
     *
     * @mbggenerated
     */
    private String batchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgzb.groupname
     *
     * @mbggenerated
     */
    private String groupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgzb.suffix
     *
     * @mbggenerated
     */
    private String suffix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgzb.oldname
     *
     * @mbggenerated
     */
    private String oldname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgzb.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgzb.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgzb.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table imgzb
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgzb.imagename
     *
     * @return the value of imgzb.imagename
     *
     * @mbggenerated
     */
    public String getImagename() {
        return imagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgzb.imagename
     *
     * @param imagename the value for imgzb.imagename
     *
     * @mbggenerated
     */
    public void setImagename(String imagename) {
        this.imagename = imagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgzb.merchid
     *
     * @return the value of imgzb.merchid
     *
     * @mbggenerated
     */
    public String getMerchid() {
        return merchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgzb.merchid
     *
     * @param merchid the value for imgzb.merchid
     *
     * @mbggenerated
     */
    public void setMerchid(String merchid) {
        this.merchid = merchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgzb.batchid
     *
     * @return the value of imgzb.batchid
     *
     * @mbggenerated
     */
    public String getBatchid() {
        return batchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgzb.batchid
     *
     * @param batchid the value for imgzb.batchid
     *
     * @mbggenerated
     */
    public void setBatchid(String batchid) {
        this.batchid = batchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgzb.groupname
     *
     * @return the value of imgzb.groupname
     *
     * @mbggenerated
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgzb.groupname
     *
     * @param groupname the value for imgzb.groupname
     *
     * @mbggenerated
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgzb.suffix
     *
     * @return the value of imgzb.suffix
     *
     * @mbggenerated
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgzb.suffix
     *
     * @param suffix the value for imgzb.suffix
     *
     * @mbggenerated
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgzb.oldname
     *
     * @return the value of imgzb.oldname
     *
     * @mbggenerated
     */
    public String getOldname() {
        return oldname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgzb.oldname
     *
     * @param oldname the value for imgzb.oldname
     *
     * @mbggenerated
     */
    public void setOldname(String oldname) {
        this.oldname = oldname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgzb.remark
     *
     * @return the value of imgzb.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgzb.remark
     *
     * @param remark the value for imgzb.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgzb.createtime
     *
     * @return the value of imgzb.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgzb.createtime
     *
     * @param createtime the value for imgzb.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgzb.updatetime
     *
     * @return the value of imgzb.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgzb.updatetime
     *
     * @param updatetime the value for imgzb.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}