package mybatis.one.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DBRecogsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recogs
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recogs
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recogs
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recogs
     *
     * @mbggenerated
     */
    public DBRecogsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recogs
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recogs
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recogs
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recogs
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recogs
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recogs
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recogs
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recogs
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recogs
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recogs
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table recogs
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSeqidIsNull() {
            addCriterion("seqid is null");
            return (Criteria) this;
        }

        public Criteria andSeqidIsNotNull() {
            addCriterion("seqid is not null");
            return (Criteria) this;
        }

        public Criteria andSeqidEqualTo(Long value) {
            addCriterion("seqid =", value, "seqid");
            return (Criteria) this;
        }

        public Criteria andSeqidNotEqualTo(Long value) {
            addCriterion("seqid <>", value, "seqid");
            return (Criteria) this;
        }

        public Criteria andSeqidGreaterThan(Long value) {
            addCriterion("seqid >", value, "seqid");
            return (Criteria) this;
        }

        public Criteria andSeqidGreaterThanOrEqualTo(Long value) {
            addCriterion("seqid >=", value, "seqid");
            return (Criteria) this;
        }

        public Criteria andSeqidLessThan(Long value) {
            addCriterion("seqid <", value, "seqid");
            return (Criteria) this;
        }

        public Criteria andSeqidLessThanOrEqualTo(Long value) {
            addCriterion("seqid <=", value, "seqid");
            return (Criteria) this;
        }

        public Criteria andSeqidIn(List<Long> values) {
            addCriterion("seqid in", values, "seqid");
            return (Criteria) this;
        }

        public Criteria andSeqidNotIn(List<Long> values) {
            addCriterion("seqid not in", values, "seqid");
            return (Criteria) this;
        }

        public Criteria andSeqidBetween(Long value1, Long value2) {
            addCriterion("seqid between", value1, value2, "seqid");
            return (Criteria) this;
        }

        public Criteria andSeqidNotBetween(Long value1, Long value2) {
            addCriterion("seqid not between", value1, value2, "seqid");
            return (Criteria) this;
        }

        public Criteria andMerchidIsNull() {
            addCriterion("merchid is null");
            return (Criteria) this;
        }

        public Criteria andMerchidIsNotNull() {
            addCriterion("merchid is not null");
            return (Criteria) this;
        }

        public Criteria andMerchidEqualTo(String value) {
            addCriterion("merchid =", value, "merchid");
            return (Criteria) this;
        }

        public Criteria andMerchidNotEqualTo(String value) {
            addCriterion("merchid <>", value, "merchid");
            return (Criteria) this;
        }

        public Criteria andMerchidGreaterThan(String value) {
            addCriterion("merchid >", value, "merchid");
            return (Criteria) this;
        }

        public Criteria andMerchidGreaterThanOrEqualTo(String value) {
            addCriterion("merchid >=", value, "merchid");
            return (Criteria) this;
        }

        public Criteria andMerchidLessThan(String value) {
            addCriterion("merchid <", value, "merchid");
            return (Criteria) this;
        }

        public Criteria andMerchidLessThanOrEqualTo(String value) {
            addCriterion("merchid <=", value, "merchid");
            return (Criteria) this;
        }

        public Criteria andMerchidLike(String value) {
            addCriterion("merchid like", value, "merchid");
            return (Criteria) this;
        }

        public Criteria andMerchidNotLike(String value) {
            addCriterion("merchid not like", value, "merchid");
            return (Criteria) this;
        }

        public Criteria andMerchidIn(List<String> values) {
            addCriterion("merchid in", values, "merchid");
            return (Criteria) this;
        }

        public Criteria andMerchidNotIn(List<String> values) {
            addCriterion("merchid not in", values, "merchid");
            return (Criteria) this;
        }

        public Criteria andMerchidBetween(String value1, String value2) {
            addCriterion("merchid between", value1, value2, "merchid");
            return (Criteria) this;
        }

        public Criteria andMerchidNotBetween(String value1, String value2) {
            addCriterion("merchid not between", value1, value2, "merchid");
            return (Criteria) this;
        }

        public Criteria andBatchidIsNull() {
            addCriterion("batchid is null");
            return (Criteria) this;
        }

        public Criteria andBatchidIsNotNull() {
            addCriterion("batchid is not null");
            return (Criteria) this;
        }

        public Criteria andBatchidEqualTo(String value) {
            addCriterion("batchid =", value, "batchid");
            return (Criteria) this;
        }

        public Criteria andBatchidNotEqualTo(String value) {
            addCriterion("batchid <>", value, "batchid");
            return (Criteria) this;
        }

        public Criteria andBatchidGreaterThan(String value) {
            addCriterion("batchid >", value, "batchid");
            return (Criteria) this;
        }

        public Criteria andBatchidGreaterThanOrEqualTo(String value) {
            addCriterion("batchid >=", value, "batchid");
            return (Criteria) this;
        }

        public Criteria andBatchidLessThan(String value) {
            addCriterion("batchid <", value, "batchid");
            return (Criteria) this;
        }

        public Criteria andBatchidLessThanOrEqualTo(String value) {
            addCriterion("batchid <=", value, "batchid");
            return (Criteria) this;
        }

        public Criteria andBatchidLike(String value) {
            addCriterion("batchid like", value, "batchid");
            return (Criteria) this;
        }

        public Criteria andBatchidNotLike(String value) {
            addCriterion("batchid not like", value, "batchid");
            return (Criteria) this;
        }

        public Criteria andBatchidIn(List<String> values) {
            addCriterion("batchid in", values, "batchid");
            return (Criteria) this;
        }

        public Criteria andBatchidNotIn(List<String> values) {
            addCriterion("batchid not in", values, "batchid");
            return (Criteria) this;
        }

        public Criteria andBatchidBetween(String value1, String value2) {
            addCriterion("batchid between", value1, value2, "batchid");
            return (Criteria) this;
        }

        public Criteria andBatchidNotBetween(String value1, String value2) {
            addCriterion("batchid not between", value1, value2, "batchid");
            return (Criteria) this;
        }

        public Criteria andZjmobileIsNull() {
            addCriterion("zjmobile is null");
            return (Criteria) this;
        }

        public Criteria andZjmobileIsNotNull() {
            addCriterion("zjmobile is not null");
            return (Criteria) this;
        }

        public Criteria andZjmobileEqualTo(String value) {
            addCriterion("zjmobile =", value, "zjmobile");
            return (Criteria) this;
        }

        public Criteria andZjmobileNotEqualTo(String value) {
            addCriterion("zjmobile <>", value, "zjmobile");
            return (Criteria) this;
        }

        public Criteria andZjmobileGreaterThan(String value) {
            addCriterion("zjmobile >", value, "zjmobile");
            return (Criteria) this;
        }

        public Criteria andZjmobileGreaterThanOrEqualTo(String value) {
            addCriterion("zjmobile >=", value, "zjmobile");
            return (Criteria) this;
        }

        public Criteria andZjmobileLessThan(String value) {
            addCriterion("zjmobile <", value, "zjmobile");
            return (Criteria) this;
        }

        public Criteria andZjmobileLessThanOrEqualTo(String value) {
            addCriterion("zjmobile <=", value, "zjmobile");
            return (Criteria) this;
        }

        public Criteria andZjmobileLike(String value) {
            addCriterion("zjmobile like", value, "zjmobile");
            return (Criteria) this;
        }

        public Criteria andZjmobileNotLike(String value) {
            addCriterion("zjmobile not like", value, "zjmobile");
            return (Criteria) this;
        }

        public Criteria andZjmobileIn(List<String> values) {
            addCriterion("zjmobile in", values, "zjmobile");
            return (Criteria) this;
        }

        public Criteria andZjmobileNotIn(List<String> values) {
            addCriterion("zjmobile not in", values, "zjmobile");
            return (Criteria) this;
        }

        public Criteria andZjmobileBetween(String value1, String value2) {
            addCriterion("zjmobile between", value1, value2, "zjmobile");
            return (Criteria) this;
        }

        public Criteria andZjmobileNotBetween(String value1, String value2) {
            addCriterion("zjmobile not between", value1, value2, "zjmobile");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andDataurlIsNull() {
            addCriterion("dataurl is null");
            return (Criteria) this;
        }

        public Criteria andDataurlIsNotNull() {
            addCriterion("dataurl is not null");
            return (Criteria) this;
        }

        public Criteria andDataurlEqualTo(String value) {
            addCriterion("dataurl =", value, "dataurl");
            return (Criteria) this;
        }

        public Criteria andDataurlNotEqualTo(String value) {
            addCriterion("dataurl <>", value, "dataurl");
            return (Criteria) this;
        }

        public Criteria andDataurlGreaterThan(String value) {
            addCriterion("dataurl >", value, "dataurl");
            return (Criteria) this;
        }

        public Criteria andDataurlGreaterThanOrEqualTo(String value) {
            addCriterion("dataurl >=", value, "dataurl");
            return (Criteria) this;
        }

        public Criteria andDataurlLessThan(String value) {
            addCriterion("dataurl <", value, "dataurl");
            return (Criteria) this;
        }

        public Criteria andDataurlLessThanOrEqualTo(String value) {
            addCriterion("dataurl <=", value, "dataurl");
            return (Criteria) this;
        }

        public Criteria andDataurlLike(String value) {
            addCriterion("dataurl like", value, "dataurl");
            return (Criteria) this;
        }

        public Criteria andDataurlNotLike(String value) {
            addCriterion("dataurl not like", value, "dataurl");
            return (Criteria) this;
        }

        public Criteria andDataurlIn(List<String> values) {
            addCriterion("dataurl in", values, "dataurl");
            return (Criteria) this;
        }

        public Criteria andDataurlNotIn(List<String> values) {
            addCriterion("dataurl not in", values, "dataurl");
            return (Criteria) this;
        }

        public Criteria andDataurlBetween(String value1, String value2) {
            addCriterion("dataurl between", value1, value2, "dataurl");
            return (Criteria) this;
        }

        public Criteria andDataurlNotBetween(String value1, String value2) {
            addCriterion("dataurl not between", value1, value2, "dataurl");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andManualresultIsNull() {
            addCriterion("manualresult is null");
            return (Criteria) this;
        }

        public Criteria andManualresultIsNotNull() {
            addCriterion("manualresult is not null");
            return (Criteria) this;
        }

        public Criteria andManualresultEqualTo(Integer value) {
            addCriterion("manualresult =", value, "manualresult");
            return (Criteria) this;
        }

        public Criteria andManualresultNotEqualTo(Integer value) {
            addCriterion("manualresult <>", value, "manualresult");
            return (Criteria) this;
        }

        public Criteria andManualresultGreaterThan(Integer value) {
            addCriterion("manualresult >", value, "manualresult");
            return (Criteria) this;
        }

        public Criteria andManualresultGreaterThanOrEqualTo(Integer value) {
            addCriterion("manualresult >=", value, "manualresult");
            return (Criteria) this;
        }

        public Criteria andManualresultLessThan(Integer value) {
            addCriterion("manualresult <", value, "manualresult");
            return (Criteria) this;
        }

        public Criteria andManualresultLessThanOrEqualTo(Integer value) {
            addCriterion("manualresult <=", value, "manualresult");
            return (Criteria) this;
        }

        public Criteria andManualresultIn(List<Integer> values) {
            addCriterion("manualresult in", values, "manualresult");
            return (Criteria) this;
        }

        public Criteria andManualresultNotIn(List<Integer> values) {
            addCriterion("manualresult not in", values, "manualresult");
            return (Criteria) this;
        }

        public Criteria andManualresultBetween(Integer value1, Integer value2) {
            addCriterion("manualresult between", value1, value2, "manualresult");
            return (Criteria) this;
        }

        public Criteria andManualresultNotBetween(Integer value1, Integer value2) {
            addCriterion("manualresult not between", value1, value2, "manualresult");
            return (Criteria) this;
        }

        public Criteria andResultIsNull() {
            addCriterion("result is null");
            return (Criteria) this;
        }

        public Criteria andResultIsNotNull() {
            addCriterion("result is not null");
            return (Criteria) this;
        }

        public Criteria andResultEqualTo(Integer value) {
            addCriterion("result =", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotEqualTo(Integer value) {
            addCriterion("result <>", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultGreaterThan(Integer value) {
            addCriterion("result >", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultGreaterThanOrEqualTo(Integer value) {
            addCriterion("result >=", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultLessThan(Integer value) {
            addCriterion("result <", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultLessThanOrEqualTo(Integer value) {
            addCriterion("result <=", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultIn(List<Integer> values) {
            addCriterion("result in", values, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotIn(List<Integer> values) {
            addCriterion("result not in", values, "result");
            return (Criteria) this;
        }

        public Criteria andResultBetween(Integer value1, Integer value2) {
            addCriterion("result between", value1, value2, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotBetween(Integer value1, Integer value2) {
            addCriterion("result not between", value1, value2, "result");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeIsNull() {
            addCriterion("receivetime is null");
            return (Criteria) this;
        }

        public Criteria andReceivetimeIsNotNull() {
            addCriterion("receivetime is not null");
            return (Criteria) this;
        }

        public Criteria andReceivetimeEqualTo(Date value) {
            addCriterion("receivetime =", value, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeNotEqualTo(Date value) {
            addCriterion("receivetime <>", value, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeGreaterThan(Date value) {
            addCriterion("receivetime >", value, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("receivetime >=", value, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeLessThan(Date value) {
            addCriterion("receivetime <", value, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeLessThanOrEqualTo(Date value) {
            addCriterion("receivetime <=", value, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeIn(List<Date> values) {
            addCriterion("receivetime in", values, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeNotIn(List<Date> values) {
            addCriterion("receivetime not in", values, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeBetween(Date value1, Date value2) {
            addCriterion("receivetime between", value1, value2, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeNotBetween(Date value1, Date value2) {
            addCriterion("receivetime not between", value1, value2, "receivetime");
            return (Criteria) this;
        }

        public Criteria andCalltimeIsNull() {
            addCriterion("calltime is null");
            return (Criteria) this;
        }

        public Criteria andCalltimeIsNotNull() {
            addCriterion("calltime is not null");
            return (Criteria) this;
        }

        public Criteria andCalltimeEqualTo(Date value) {
            addCriterion("calltime =", value, "calltime");
            return (Criteria) this;
        }

        public Criteria andCalltimeNotEqualTo(Date value) {
            addCriterion("calltime <>", value, "calltime");
            return (Criteria) this;
        }

        public Criteria andCalltimeGreaterThan(Date value) {
            addCriterion("calltime >", value, "calltime");
            return (Criteria) this;
        }

        public Criteria andCalltimeGreaterThanOrEqualTo(Date value) {
            addCriterion("calltime >=", value, "calltime");
            return (Criteria) this;
        }

        public Criteria andCalltimeLessThan(Date value) {
            addCriterion("calltime <", value, "calltime");
            return (Criteria) this;
        }

        public Criteria andCalltimeLessThanOrEqualTo(Date value) {
            addCriterion("calltime <=", value, "calltime");
            return (Criteria) this;
        }

        public Criteria andCalltimeIn(List<Date> values) {
            addCriterion("calltime in", values, "calltime");
            return (Criteria) this;
        }

        public Criteria andCalltimeNotIn(List<Date> values) {
            addCriterion("calltime not in", values, "calltime");
            return (Criteria) this;
        }

        public Criteria andCalltimeBetween(Date value1, Date value2) {
            addCriterion("calltime between", value1, value2, "calltime");
            return (Criteria) this;
        }

        public Criteria andCalltimeNotBetween(Date value1, Date value2) {
            addCriterion("calltime not between", value1, value2, "calltime");
            return (Criteria) this;
        }

        public Criteria andRecogtimeIsNull() {
            addCriterion("recogtime is null");
            return (Criteria) this;
        }

        public Criteria andRecogtimeIsNotNull() {
            addCriterion("recogtime is not null");
            return (Criteria) this;
        }

        public Criteria andRecogtimeEqualTo(Date value) {
            addCriterion("recogtime =", value, "recogtime");
            return (Criteria) this;
        }

        public Criteria andRecogtimeNotEqualTo(Date value) {
            addCriterion("recogtime <>", value, "recogtime");
            return (Criteria) this;
        }

        public Criteria andRecogtimeGreaterThan(Date value) {
            addCriterion("recogtime >", value, "recogtime");
            return (Criteria) this;
        }

        public Criteria andRecogtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("recogtime >=", value, "recogtime");
            return (Criteria) this;
        }

        public Criteria andRecogtimeLessThan(Date value) {
            addCriterion("recogtime <", value, "recogtime");
            return (Criteria) this;
        }

        public Criteria andRecogtimeLessThanOrEqualTo(Date value) {
            addCriterion("recogtime <=", value, "recogtime");
            return (Criteria) this;
        }

        public Criteria andRecogtimeIn(List<Date> values) {
            addCriterion("recogtime in", values, "recogtime");
            return (Criteria) this;
        }

        public Criteria andRecogtimeNotIn(List<Date> values) {
            addCriterion("recogtime not in", values, "recogtime");
            return (Criteria) this;
        }

        public Criteria andRecogtimeBetween(Date value1, Date value2) {
            addCriterion("recogtime between", value1, value2, "recogtime");
            return (Criteria) this;
        }

        public Criteria andRecogtimeNotBetween(Date value1, Date value2) {
            addCriterion("recogtime not between", value1, value2, "recogtime");
            return (Criteria) this;
        }

        public Criteria andMerchidLikeInsensitive(String value) {
            addCriterion("upper(merchid) like", value.toUpperCase(), "merchid");
            return (Criteria) this;
        }

        public Criteria andBatchidLikeInsensitive(String value) {
            addCriterion("upper(batchid) like", value.toUpperCase(), "batchid");
            return (Criteria) this;
        }

        public Criteria andZjmobileLikeInsensitive(String value) {
            addCriterion("upper(zjmobile) like", value.toUpperCase(), "zjmobile");
            return (Criteria) this;
        }

        public Criteria andMobileLikeInsensitive(String value) {
            addCriterion("upper(mobile) like", value.toUpperCase(), "mobile");
            return (Criteria) this;
        }

        public Criteria andDataurlLikeInsensitive(String value) {
            addCriterion("upper(dataurl) like", value.toUpperCase(), "dataurl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table recogs
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table recogs
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}