package mybatis.one.po;

import java.io.Serializable;

public class DBTmpPhone implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmpPhone.seqid
     *
     * @mbggenerated
     */
    private Integer seqid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmpPhone.merchid
     *
     * @mbggenerated
     */
    private String merchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmpPhone.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tmpPhone
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmpPhone.seqid
     *
     * @return the value of tmpPhone.seqid
     *
     * @mbggenerated
     */
    public Integer getSeqid() {
        return seqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmpPhone.seqid
     *
     * @param seqid the value for tmpPhone.seqid
     *
     * @mbggenerated
     */
    public void setSeqid(Integer seqid) {
        this.seqid = seqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmpPhone.merchid
     *
     * @return the value of tmpPhone.merchid
     *
     * @mbggenerated
     */
    public String getMerchid() {
        return merchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmpPhone.merchid
     *
     * @param merchid the value for tmpPhone.merchid
     *
     * @mbggenerated
     */
    public void setMerchid(String merchid) {
        this.merchid = merchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmpPhone.phone
     *
     * @return the value of tmpPhone.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmpPhone.phone
     *
     * @param phone the value for tmpPhone.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
}