package mybatis.one.po;

import java.io.Serializable;

public class DBZNContact implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zncontact.seqid
     *
     * @mbggenerated
     */
    private Integer seqid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zncontact.batchid
     *
     * @mbggenerated
     */
    private String batchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zncontact.caseno
     *
     * @mbggenerated
     */
    private String caseno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zncontact.serino
     *
     * @mbggenerated
     */
    private String serino;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zncontact.prelation
     *
     * @mbggenerated
     */
    private String prelation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zncontact.pname
     *
     * @mbggenerated
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zncontact.ptel
     *
     * @mbggenerated
     */
    private String ptel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zncontact.telck
     *
     * @mbggenerated
     */
    private String telck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zncontact.ptel1
     *
     * @mbggenerated
     */
    private String ptel1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zncontact.tel1ck
     *
     * @mbggenerated
     */
    private String tel1ck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zncontact
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zncontact.seqid
     *
     * @return the value of zncontact.seqid
     *
     * @mbggenerated
     */
    public Integer getSeqid() {
        return seqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zncontact.seqid
     *
     * @param seqid the value for zncontact.seqid
     *
     * @mbggenerated
     */
    public void setSeqid(Integer seqid) {
        this.seqid = seqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zncontact.batchid
     *
     * @return the value of zncontact.batchid
     *
     * @mbggenerated
     */
    public String getBatchid() {
        return batchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zncontact.batchid
     *
     * @param batchid the value for zncontact.batchid
     *
     * @mbggenerated
     */
    public void setBatchid(String batchid) {
        this.batchid = batchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zncontact.caseno
     *
     * @return the value of zncontact.caseno
     *
     * @mbggenerated
     */
    public String getCaseno() {
        return caseno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zncontact.caseno
     *
     * @param caseno the value for zncontact.caseno
     *
     * @mbggenerated
     */
    public void setCaseno(String caseno) {
        this.caseno = caseno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zncontact.serino
     *
     * @return the value of zncontact.serino
     *
     * @mbggenerated
     */
    public String getSerino() {
        return serino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zncontact.serino
     *
     * @param serino the value for zncontact.serino
     *
     * @mbggenerated
     */
    public void setSerino(String serino) {
        this.serino = serino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zncontact.prelation
     *
     * @return the value of zncontact.prelation
     *
     * @mbggenerated
     */
    public String getPrelation() {
        return prelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zncontact.prelation
     *
     * @param prelation the value for zncontact.prelation
     *
     * @mbggenerated
     */
    public void setPrelation(String prelation) {
        this.prelation = prelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zncontact.pname
     *
     * @return the value of zncontact.pname
     *
     * @mbggenerated
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zncontact.pname
     *
     * @param pname the value for zncontact.pname
     *
     * @mbggenerated
     */
    public void setPname(String pname) {
        this.pname = pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zncontact.ptel
     *
     * @return the value of zncontact.ptel
     *
     * @mbggenerated
     */
    public String getPtel() {
        return ptel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zncontact.ptel
     *
     * @param ptel the value for zncontact.ptel
     *
     * @mbggenerated
     */
    public void setPtel(String ptel) {
        this.ptel = ptel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zncontact.telck
     *
     * @return the value of zncontact.telck
     *
     * @mbggenerated
     */
    public String getTelck() {
        return telck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zncontact.telck
     *
     * @param telck the value for zncontact.telck
     *
     * @mbggenerated
     */
    public void setTelck(String telck) {
        this.telck = telck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zncontact.ptel1
     *
     * @return the value of zncontact.ptel1
     *
     * @mbggenerated
     */
    public String getPtel1() {
        return ptel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zncontact.ptel1
     *
     * @param ptel1 the value for zncontact.ptel1
     *
     * @mbggenerated
     */
    public void setPtel1(String ptel1) {
        this.ptel1 = ptel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zncontact.tel1ck
     *
     * @return the value of zncontact.tel1ck
     *
     * @mbggenerated
     */
    public String getTel1ck() {
        return tel1ck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zncontact.tel1ck
     *
     * @param tel1ck the value for zncontact.tel1ck
     *
     * @mbggenerated
     */
    public void setTel1ck(String tel1ck) {
        this.tel1ck = tel1ck;
    }
}