package mybatis.one.po;

import java.io.Serializable;
import java.util.Date;

public class DBZNUpdateInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column znupdateinfo.seqid
     *
     * @mbggenerated
     */
    private Long seqid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column znupdateinfo.caseno
     *
     * @mbggenerated
     */
    private String caseno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column znupdateinfo.ptel
     *
     * @mbggenerated
     */
    private String ptel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column znupdateinfo.ptel1
     *
     * @mbggenerated
     */
    private String ptel1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column znupdateinfo.telck
     *
     * @mbggenerated
     */
    private String telck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column znupdateinfo.tel1ck
     *
     * @mbggenerated
     */
    private String tel1ck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column znupdateinfo.pname
     *
     * @mbggenerated
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column znupdateinfo.batchid
     *
     * @mbggenerated
     */
    private String batchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column znupdateinfo.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column znupdateinfo.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table znupdateinfo
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column znupdateinfo.seqid
     *
     * @return the value of znupdateinfo.seqid
     *
     * @mbggenerated
     */
    public Long getSeqid() {
        return seqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column znupdateinfo.seqid
     *
     * @param seqid the value for znupdateinfo.seqid
     *
     * @mbggenerated
     */
    public void setSeqid(Long seqid) {
        this.seqid = seqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column znupdateinfo.caseno
     *
     * @return the value of znupdateinfo.caseno
     *
     * @mbggenerated
     */
    public String getCaseno() {
        return caseno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column znupdateinfo.caseno
     *
     * @param caseno the value for znupdateinfo.caseno
     *
     * @mbggenerated
     */
    public void setCaseno(String caseno) {
        this.caseno = caseno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column znupdateinfo.ptel
     *
     * @return the value of znupdateinfo.ptel
     *
     * @mbggenerated
     */
    public String getPtel() {
        return ptel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column znupdateinfo.ptel
     *
     * @param ptel the value for znupdateinfo.ptel
     *
     * @mbggenerated
     */
    public void setPtel(String ptel) {
        this.ptel = ptel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column znupdateinfo.ptel1
     *
     * @return the value of znupdateinfo.ptel1
     *
     * @mbggenerated
     */
    public String getPtel1() {
        return ptel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column znupdateinfo.ptel1
     *
     * @param ptel1 the value for znupdateinfo.ptel1
     *
     * @mbggenerated
     */
    public void setPtel1(String ptel1) {
        this.ptel1 = ptel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column znupdateinfo.telck
     *
     * @return the value of znupdateinfo.telck
     *
     * @mbggenerated
     */
    public String getTelck() {
        return telck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column znupdateinfo.telck
     *
     * @param telck the value for znupdateinfo.telck
     *
     * @mbggenerated
     */
    public void setTelck(String telck) {
        this.telck = telck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column znupdateinfo.tel1ck
     *
     * @return the value of znupdateinfo.tel1ck
     *
     * @mbggenerated
     */
    public String getTel1ck() {
        return tel1ck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column znupdateinfo.tel1ck
     *
     * @param tel1ck the value for znupdateinfo.tel1ck
     *
     * @mbggenerated
     */
    public void setTel1ck(String tel1ck) {
        this.tel1ck = tel1ck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column znupdateinfo.pname
     *
     * @return the value of znupdateinfo.pname
     *
     * @mbggenerated
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column znupdateinfo.pname
     *
     * @param pname the value for znupdateinfo.pname
     *
     * @mbggenerated
     */
    public void setPname(String pname) {
        this.pname = pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column znupdateinfo.batchid
     *
     * @return the value of znupdateinfo.batchid
     *
     * @mbggenerated
     */
    public String getBatchid() {
        return batchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column znupdateinfo.batchid
     *
     * @param batchid the value for znupdateinfo.batchid
     *
     * @mbggenerated
     */
    public void setBatchid(String batchid) {
        this.batchid = batchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column znupdateinfo.phone
     *
     * @return the value of znupdateinfo.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column znupdateinfo.phone
     *
     * @param phone the value for znupdateinfo.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column znupdateinfo.createtime
     *
     * @return the value of znupdateinfo.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column znupdateinfo.createtime
     *
     * @param createtime the value for znupdateinfo.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}